# ══════════════════════════════════════════════════════════════════
# RAPTORS — vultures, hawks, eagles, falcons
# ══════════════════════════════════════════════════════════════════

S("Turkey Vulture", "Cathartes aura", "Cathartiformes", "🦅", ["raptor"],
  "62–81 cm", "0.85–2.26 kg", "160–183 cm", "~16 yr",
  "NE:c85 SE:c90 MW:c85 NW:c80 SW:c85 CA:c88 TX:c88",
  "Finds carrion by smell — a genuinely rare ability among birds, and so acute that gas companies have used it to find pipeline leaks by adding the same compound vultures detect. Soars for hours without a wingbeat.",
  "All dark brown-black with a bare red head and silvery flight feathers below. Holds wings in a shallow V and rocks side to side.",
  "Identical to the male. Sexes cannot be told apart in the field.",
  ["Carrion"],
  "Open country of every kind — farmland, roadsides, forest edge, and desert. Roosts communally in big trees."),

S("Black Vulture", "Coragyps atratus", "Cathartiformes", "🦅", ["raptor"],
  "56–74 cm", "1.6–2.75 kg", "133–160 cm", "~10 yr",
  "SE:c85 MW:u50 TX:c80 NE:u45",
  "Has a poor sense of smell, so it watches Turkey Vultures and follows them down to a carcass — then bullies them off it. Expanding steadily northward.",
  "All black with a bare grey wrinkled head, short square tail, and white patches at the wingtips. Flaps often, in quick shallow beats.",
  "Identical to the male. Highly social; roosts and forages in family groups.",
  ["Carrion", "Refuse", "Occasionally live prey"],
  "Open and semi-open country, especially near towns, landfills, and highways."),

S("Osprey", "Pandion haliaetus", "Accipitriformes", "🦅", ["raptor"],
  "55–58 cm", "1.2–2 kg", "147–180 cm", "15–20 yr",
  "NE:c60 SE:c70 MW:u55 NW:c65 SW:u50 CA:c60 TX:u55",
  "A fish specialist found on every continent but Antarctica. It can reverse an outer toe to grip a fish with two toes front and two back, and its footpads are studded with spines for holding slippery prey.",
  "Dark brown above, white below, with a white head crossed by a broad dark eye stripe. Wings crooked at the wrist in flight.",
  "Very similar, but usually with a heavier brown 'necklace' of streaking across the breast. Larger than the male.",
  ["Fish (almost exclusively)"],
  "Any large water with fish — coasts, lakes, rivers, reservoirs. Nests on platforms, poles, and dead trees."),

S("Bald Eagle", "Haliaeetus leucocephalus", "Accipitriformes", "🦅", ["raptor"],
  "70–102 cm", "3–6.3 kg", "182–244 cm", "20–30 yr",
  "NE:u60 SE:c65 MW:u60 NW:c75 SW:u45 CA:u60 TX:u55",
  "Brought back from the edge by the DDT ban and the Endangered Species Act — from a few hundred pairs in the lower 48 to tens of thousands today. The white head and tail don't appear until about year five.",
  "Unmistakable: white head and tail, dark brown body, and a massive yellow bill.",
  "Identical in plumage but distinctly larger — the most pronounced size difference of any North American raptor.",
  ["Fish", "Waterfowl", "Carrion", "Small mammals"],
  "Always near big water — coasts, large rivers, and reservoirs. Nests in huge trees with a commanding view."),

S("Golden Eagle", "Aquila chrysaetos", "Accipitriformes", "🦅", ["raptor"],
  "66–102 cm", "3–6.4 kg", "185–220 cm", "~30 yr",
  "NW:u50 SW:u50 CA:u45 MW:r30 TX:r30",
  "A bird of open western country and one of the fastest animals alive — it can stoop on prey at nearly 200 mph. Ranges over vast territories and rarely tolerates company.",
  "All dark brown with a golden wash over the nape and crown. Soars on flat or slightly raised wings.",
  "Identical to the male, larger. Juveniles show bold white patches at the wing base and tail base.",
  ["Rabbits", "Ground squirrels", "Marmots", "Carrion", "Birds"],
  "Open and rugged country — mountains, canyons, sagebrush, and grassland. Nests on cliffs and in large trees."),

S("Northern Harrier", "Circus hudsonius", "Accipitriformes", "🦅", ["raptor"],
  "41–52 cm", "300–750 g", "97–122 cm", "~16 yr",
  "NE:u55 SE:u55 MW:c65 NW:c65 SW:u55 CA:c65 TX:c65",
  "Hunts by ear as much as by eye — it has an owl-like facial disc that funnels sound, letting it find voles in thick grass. Quarters low over fields with wings held in a lazy V.",
  "Pale grey above, white below, with black wingtips — the 'grey ghost'. Bold white rump patch.",
  "Brown above and streaky buff below, much bigger and browner than the male. Same white rump.",
  ["Voles", "Mice", "Small birds", "Frogs"],
  "Marshes, wet meadows, grassland, and farm fields. Nests on the ground in dense cover."),

S("Sharp-shinned Hawk", "Accipiter striatus", "Accipitriformes", "🦅", ["raptor"],
  "24–34 cm", "87–218 g", "43–56 cm", "~5 yr",
  "NE:u50 SE:u50 MW:u50 NW:u50 SW:u45 CA:u50 TX:u45",
  "A tiny, hyper-agile forest hawk built to chase songbirds through branches. The smallest accipiter in North America, and a familiar terror at winter feeders.",
  "Blue-grey above, finely rusty-barred below, with a small head, thin legs, and a square-tipped tail. Red eye when adult.",
  "Same pattern but noticeably larger — a big female approaches a small male Cooper's Hawk in size.",
  ["Small birds", "Occasionally rodents and insects"],
  "Dense forest and woodland edge; increasingly suburban yards with feeders in winter."),

S("Cooper's Hawk", "Accipiter cooperii", "Accipitriformes", "🦅", ["raptor"],
  "35–50 cm", "280–680 g", "62–90 cm", "~12 yr",
  "NE:u55 SE:c60 MW:u60 NW:u55 SW:u55 CA:c60 TX:u55",
  "The classic backyard bird-hawk. It has adapted so well to suburbs that urban Cooper's Hawks often survive better than forest ones — the feeders are, from the hawk's view, a buffet.",
  "Blue-grey above, rusty-barred below, with a dark cap contrasting with a paler nape, and a long rounded tail.",
  "Same pattern, browner-backed, and substantially larger — approaching crow size.",
  ["Songbirds", "Doves", "Starlings", "Squirrels", "Chipmunks"],
  "Mature woodland, woodland edge, parks, and leafy suburbs. Hunts from concealed perches."),

S("Red-shouldered Hawk", "Buteo lineatus", "Accipitriformes", "🦅", ["raptor"],
  "43–61 cm", "550–700 g", "94–111 cm", "~15 yr",
  "NE:c65 SE:c75 MW:u55 CA:c70 TX:u55",
  "A loud, dramatic hawk of wet woodlands. Its ringing 'kee-aah' is one of the most frequently mimicked calls in the forest — Blue Jays imitate it constantly, apparently to clear feeders.",
  "Rufous-barred underparts, rusty shoulder patches, and a boldly black-and-white banded tail. Pale crescent 'windows' near the wingtips in flight.",
  "Identical plumage, larger. The translucent wing crescents are the best flight mark for both sexes.",
  ["Frogs", "Snakes", "Crayfish", "Voles", "Small birds"],
  "Wet bottomland forest, riparian woods, and swamps. Also mature suburbs with big trees."),

S("Broad-winged Hawk", "Buteo platypterus", "Accipitriformes", "🦅", ["raptor"],
  "34–44 cm", "265–560 g", "81–100 cm", "~12 yr",
  "NE:c60 SE:u55 MW:u55 TX:u50",
  "A small woodland buteo that migrates in spectacular swirling flocks called kettles — tens of thousands can pass a hawk-watch site in a single September day, bound for South America.",
  "Compact brown hawk with rusty barring on the breast and a tail crossed by broad black-and-white bands.",
  "Identical to the male. Both are far more often heard — a thin, plaintive whistle — than seen in summer.",
  ["Frogs", "Toads", "Snakes", "Small mammals", "Insects"],
  "Interior deciduous and mixed forest. Nests in dense woods, hunts along openings and roads."),

S("Red-tailed Hawk", "Buteo jamaicensis", "Accipitriformes", "🦅", ["raptor"],
  "45–65 cm", "690–1600 g", "110–145 cm", "~20 yr",
  "NE:c92 SE:c88 MW:c92 NW:c88 SW:c88 CA:c92 TX:c90",
  "The default large hawk of North America, and the one on every highway light pole. Its piercing scream is so iconic that Hollywood dubs it over footage of Bald Eagles, which actually sound rather weak.",
  "Brown above, pale below with a dark belly band, and a brick-red tail. Extremely variable across its range.",
  "Identical plumage, larger and heavier. The red tail is diagnostic in adults of both sexes.",
  ["Voles", "Rabbits", "Ground squirrels", "Snakes", "Birds"],
  "Almost anywhere with an open hunting field and a high perch — farmland, roadsides, desert, and city parks."),

S("Swainson's Hawk", "Buteo swainsoni", "Accipitriformes", "🦅", ["raptor"],
  "43–56 cm", "0.6–1.7 kg", "117–137 cm", "~16 yr",
  "MW:u55 NW:u55 SW:c65 CA:u55 TX:c60",
  "Makes one of the longest migrations of any raptor — from the western plains to the pampas of Argentina, in flocks of thousands. On the wintering grounds it switches almost entirely to eating grasshoppers.",
  "Slim hawk with a dark chest bib, white throat, and long pointed wings held in a V. Dark flight feathers contrast with pale wing linings.",
  "Identical to the male. A dark morph occurs and can be confusing.",
  ["Grasshoppers", "Ground squirrels", "Voles", "Snakes"],
  "Open prairie, grassland, and agricultural country of the west. Nests in lone trees and shelterbelts."),

S("American Kestrel", "Falco sparverius", "Falconiformes", "🦅", ["raptor"],
  "19–21 cm", "80–165 g", "51–61 cm", "~5 yr",
  "NE:u45 SE:u55 MW:u55 NW:u55 SW:c65 CA:c65 TX:c65",
  "The smallest and most colorful falcon in North America, and in worrying decline. It can see ultraviolet light, which makes the urine trails of voles glow like runway lights.",
  "Rusty back and tail, blue-grey wings, a rufous crown, and two bold black 'sideburn' stripes on a white face.",
  "Rusty-brown wings as well as back, all finely barred, with streaked underparts. Same facial pattern.",
  ["Grasshoppers", "Voles", "Mice", "Small birds", "Lizards"],
  "Open country — farmland, roadsides, meadows, and deserts. Nests in cavities; readily uses nest boxes."),

S("Peregrine Falcon", "Falco peregrinus", "Falconiformes", "🦅", ["raptor"],
  "34–58 cm", "0.33–1 kg", "74–120 cm", "~15 yr",
  "NE:u45 SE:u45 MW:u40 NW:u45 SW:u40 CA:u50 TX:u40",
  "The fastest animal on the planet — a stooping Peregrine has been clocked over 240 mph. Wiped out east of the Rockies by DDT, then restored partly by releasing birds onto city skyscrapers, which serve nicely as cliffs.",
  "Slate-grey above, barred white below, with a heavy black 'helmet' and moustache mark. Long pointed wings.",
  "Identical plumage, up to a third larger than the male.",
  ["Pigeons", "Shorebirds", "Ducks", "Songbirds"],
  "Cliffs, coasts, and city skyscrapers. Hunts over open ground, water, and downtown streets alike."),


# ══════════════════════════════════════════════════════════════════
# OWLS
# ══════════════════════════════════════════════════════════════════

S("Great Horned Owl", "Bubo virginianus", "Strigiformes", "🦉", ["raptor"],
  "43–64 cm", "0.9–2.5 kg", "101–145 cm", "~13 yr",
  "NE:c75 SE:c75 MW:c78 NW:c75 SW:c78 CA:c78 TX:c78",
  "The continent's most powerful and adaptable owl, with a grip strength of over 300 psi. It's one of the very few predators that regularly kills skunks — owls have a poor sense of smell.",
  "Big, barrel-shaped, mottled grey-brown with prominent ear tufts, a white throat bib, and huge yellow eyes.",
  "Identical in plumage but larger. She has the deeper body but he has the deeper hoot.",
  ["Rabbits", "Rodents", "Skunks", "Birds", "Reptiles"],
  "Nearly every habitat on the continent — forest, desert, swamp, farmland, and city park."),

S("Barred Owl", "Strix varia", "Strigiformes", "🦉", ["raptor"],
  "40–63 cm", "0.5–1 kg", "96–125 cm", "~10 yr",
  "NE:c70 SE:c75 MW:c65 NW:u55",
  "The 'who-cooks-for-you' owl, and the most vocal of the large owls. Has expanded west in the last century, where it now outcompetes and displaces the endangered Spotted Owl.",
  "Mottled grey-brown with horizontal barring on the chest and vertical streaks on the belly. Dark eyes and no ear tufts.",
  "Identical to the male, slightly larger. Both call year-round, often in raucous duets.",
  ["Mice", "Voles", "Crayfish", "Frogs", "Small birds"],
  "Mature moist forest, wooded swamps, and river bottomland. Also large forested suburbs."),

S("Eastern Screech-Owl", "Megascops asio", "Strigiformes", "🦉", ["raptor"],
  "16–25 cm", "121–244 g", "48–61 cm", "~8 yr",
  "NE:c65 SE:c70 MW:c65 TX:c65",
  "A tiny owl hiding in plain sight across the East — often roosting in a hole in a suburban shade tree. Comes in a grey morph and a rufous morph, sometimes in the same brood.",
  "Small, stocky, with prominent ear tufts and yellow eyes. Bark-patterned grey or rusty red plumage.",
  "Identical plumage, slightly larger. The whinnying, descending call is unmistakable at night.",
  ["Insects", "Mice", "Songbirds", "Crayfish", "Earthworms"],
  "Woodlands, orchards, parks, and leafy neighborhoods. Nests in cavities and readily uses nest boxes."),

S("American Barn Owl", "Tyto alba", "Strigiformes", "🦉", ["raptor"],
  "33–40 cm", "470 g", "107 cm", "~4 yr",
  "SE:u50 MW:r25 SW:u50 CA:u55 TX:u50 NE:r15",
  "Its heart-shaped face is a parabolic dish that funnels sound to asymmetrically placed ears, letting it strike prey in total darkness by hearing alone. Declining sharply where rodenticides are used.",
  "Ghostly pale — white heart-shaped face, golden-buff back, and white underparts with fine speckling. Dark eyes.",
  "Typically more heavily speckled and washed buff-orange below than the male.",
  ["Voles", "Mice", "Shrews", "Rats"],
  "Open farmland, grassland, and marsh edge. Nests in barns, silos, church towers, and nest boxes."),

S("Burrowing Owl", "Athene cunicularia", "Strigiformes", "🦉", ["raptor"],
  "19–28 cm", "150 g", "50–61 cm", "~9 yr",
  "SW:c65 CA:u55 TX:u55 MW:u45 NW:u45",
  "A long-legged, ground-dwelling owl active by day, living in burrows dug by prairie dogs and ground squirrels. It lines the entrance with dung, which attracts dung beetles it then eats.",
  "Small, round-headed, sandy-brown with white spotting, long bare legs, and bright yellow eyes.",
  "Identical to the male, though she often becomes darker while he bleaches paler in the sun.",
  ["Insects", "Beetles", "Rodents", "Lizards"],
  "Open grassland, prairie, desert, and airfields — anywhere with burrows and short vegetation."),


# ══════════════════════════════════════════════════════════════════
# DOVES · SWIFTS · HUMMINGBIRDS
# ══════════════════════════════════════════════════════════════════

S("Rock Pigeon", "Columba livia", "Columbiformes", "🕊️", ["songbird"],
  "29–37 cm", "238–380 g", "62–68 cm", "~6 yr",
  "NE:c96 SE:c92 MW:c95 NW:c92 SW:c90 CA:c95 TX:c92",
  "Domesticated for thousands of years as food, messenger, and racer, then gone feral worldwide. Navigates using the sun, the Earth's magnetic field, and possibly infrasound — a genuinely remarkable animal we mostly ignore.",
  "Endlessly variable, but classically blue-grey with a white rump, two black wingbars, and an iridescent green-purple neck.",
  "Nearly identical, with slightly less neck iridescence. Both sexes feed young on 'crop milk'.",
  ["Seeds", "Grain", "Bread", "Refuse"],
  "Cities, bridges, farmyards, and grain elevators — skyscrapers substitute for ancestral cliffs."),

S("Mourning Dove", "Zenaida macroura", "Columbiformes", "🕊️", ["songbird"],
  "28–33 cm", "112 g", "45 cm", "~1.5 yr",
  "NE:c92 SE:c92 MW:c95 NW:c88 SW:c90 CA:c92 TX:c92",
  "One of the most abundant birds on the continent, with a population over 300 million. The mournful cooing is often mistaken for an owl. Can fly 55 mph, and the wings whistle sharply on takeoff.",
  "Slender and long-tailed, soft pinkish-buff, with black spots on the wings and a small round head.",
  "Nearly identical, marginally duller and browner with less neck iridescence.",
  ["Seeds", "Grain", "Millet", "Sunflower"],
  "Open and semi-open country of every kind — farms, suburbs, parks, roadsides, and desert."),

S("Eurasian Collared-Dove", "Streptopelia decaocto", "Columbiformes", "🕊️", ["songbird"],
  "29–33 cm", "125–240 g", "48–54 cm", "~3 yr",
  "SE:c75 MW:c65 SW:c70 CA:c65 TX:c75 NW:u55 NE:u45",
  "Escaped from a pet shop in the Bahamas in the 1970s, reached Florida, and has since swept across the continent — one of the fastest bird colonizations ever recorded.",
  "Pale sandy-grey with a black half-collar on the hindneck and a square-tipped tail.",
  "Identical to the male. Both give a monotonous three-note coo, quite unlike a Mourning Dove.",
  ["Seeds", "Grain", "Berries"],
  "Towns, suburbs, farmyards, and grain silos. Closely tied to human settlement."),

S("White-winged Dove", "Zenaida asiatica", "Columbiformes", "🕊️", ["songbird"],
  "28–33 cm", "150 g", "48 cm", "~10 yr",
  "SW:c75 TX:c80 CA:u50 SE:u45",
  "A dove of the desert Southwest that has expanded rapidly into towns. In Sonoran desert it's a key pollinator and seed disperser of the saguaro cactus, whose fruit it feeds on heavily.",
  "Sandy-brown with a bold white wing stripe, a blue eye-ring, and a black mark on the cheek.",
  "Nearly identical, typically with slightly less neck iridescence.",
  ["Seeds", "Grain", "Cactus fruit", "Berries"],
  "Desert scrub, mesquite, citrus groves, and increasingly urban parks and suburbs."),

S("Chimney Swift", "Chaetura pelagica", "Apodiformes", "🐦", ["songbird"],
  "12–15 cm", "17–30 g", "27–30 cm", "~10 yr",
  "NE:c70 SE:c75 MW:c70 TX:c65",
  "A 'flying cigar' that spends virtually its whole life airborne — it cannot perch, only cling to vertical walls. Autumn roosts of thousands funnel into a single chimney at dusk, a genuine spectacle.",
  "Uniform sooty grey-brown with a slightly paler throat, long curved wings, and a stubby tail. Chattering, twittering calls.",
  "Identical to the male; the sexes can't be separated in the field.",
  ["Flying insects", "Gnats", "Flies", "Flying ants"],
  "The open sky above almost anything. Nests and roosts inside chimneys, air shafts, and hollow trees."),

S("Ruby-throated Hummingbird", "Archilochus colubris", "Apodiformes", "🐦", ["songbird"],
  "7–9 cm", "2–6 g", "8–11 cm", "3–5 yr",
  "NE:c65 SE:c70 MW:c65 TX:c60",
  "The only hummingbird that breeds east of the Great Plains. It crosses 500 miles of open Gulf of Mexico in a single flight, powered entirely by fat it stored beforehand — doubling its body weight to do it.",
  "Iridescent emerald above with a brilliant ruby gorget that flashes or looks black depending on the light.",
  "Green above, white below, with a plain throat and white-tipped outer tail feathers. Slightly larger than the male.",
  ["Nectar", "Small insects", "Spiders", "Tree sap"],
  "Gardens, woodland edge, and parks with tubular flowers. Readily comes to sugar-water feeders."),

S("Anna's Hummingbird", "Calypte anna", "Apodiformes", "🐦", ["songbird"],
  "9–11 cm", "3–6 g", "12 cm", "~8 yr",
  "CA:c88 NW:c65 SW:u55",
  "The only hummingbird that stays on the Pacific coast year-round. In his display dive the male climbs 130 feet and plummets, producing a loud chirp with his tail feathers at the bottom — not with his voice.",
  "Iridescent rose-red over the entire head and throat, not just the throat — unique among common North American hummingbirds.",
  "Green above, grey below, usually with a small central patch of red flecks on the throat.",
  ["Nectar", "Small insects", "Tree sap"],
  "Gardens, parks, chaparral, and eucalyptus groves. Abundant in suburban California."),

S("Rufous Hummingbird", "Selasphorus rufus", "Apodiformes", "🐦", ["songbird"],
  "7–9 cm", "2–5 g", "11 cm", "~8 yr",
  "NW:c70 CA:u55 SW:u55",
  "Makes the longest migration of any bird relative to its size — up to 3,900 miles each way, from Alaska to Mexico. Ferociously territorial, it will drive off hummingbirds twice its size.",
  "Glowing coppery-orange overall with a brilliant orange-red gorget. Unmistakable when lit.",
  "Green above with rufous flanks and a rufous-washed tail base, often with a small orange throat spot.",
  ["Nectar", "Small insects", "Tree sap"],
  "Forest openings, meadows, and mountain slopes. Follows the bloom of wildflowers up the mountains in late summer."),
