# ══════════════════════════════════════════════════════════════════
# WATERBIRDS — herons, egrets, cranes, grebes, cormorants, pelicans
# ══════════════════════════════════════════════════════════════════

S("Great Blue Heron", "Ardea herodias", "Pelecaniformes", "🐦", ["waterfowl"],
  "91–137 cm", "2–3.6 kg", "167–201 cm", "~15 yr",
  "NE:c88 SE:c90 MW:c85 NW:c85 SW:c75 CA:c88 TX:c85",
  "The largest heron in North America, standing over four feet tall, yet weighing only five or six pounds thanks to hollow bones. Hunts by standing motionless, then striking with a spear-like bill.",
  "Slate-grey body, white face with a black plume trailing from the eye, a dagger-like yellow bill, and rusty thighs.",
  "Identical to the male in plumage, slightly smaller on average. Both sexes grow ornate chest plumes when breeding.",
  ["Fish", "Frogs", "Snakes", "Voles", "Crayfish"],
  "Any water at all — lakes, rivers, marshes, estuaries, even wet fields. Nests colonially in tall trees."),

S("Great Egret", "Ardea alba", "Pelecaniformes", "🐦", ["waterfowl"],
  "80–104 cm", "0.7–1.5 kg", "131–145 cm", "~15 yr",
  "NE:c65 SE:c90 MW:c65 NW:u45 SW:u55 CA:c75 TX:c88",
  "Nearly wiped out in the 1800s when its breeding plumes were worth more than gold to the hat trade. The outrage helped launch the Audubon Society, and the bird became its symbol.",
  "All white with a heavy yellow bill and black legs and feet. Grows long, gauzy back plumes when breeding.",
  "Identical to the male. Both sexes display the trailing plumes during courtship.",
  ["Fish", "Frogs", "Crayfish", "Insects", "Small mammals"],
  "Marshes, ponds, tidal flats, and flooded fields. Nests in colonies, often with other herons."),

S("Snowy Egret", "Egretta thula", "Pelecaniformes", "🐦", ["waterfowl"],
  "56–66 cm", "370 g", "100 cm", "~17 yr",
  "SE:c80 MW:u40 SW:u55 CA:c70 TX:c85 NE:u45",
  "The 'golden slippers' bird — it shuffles its bright yellow feet through the mud to flush out prey, then snatches it. More active and animated than the larger egrets.",
  "All white with a slender black bill, black legs, and vivid yellow feet. Wispy recurved plumes when breeding.",
  "Identical to the male, including the yellow feet and delicate breeding plumes.",
  ["Small fish", "Crustaceans", "Insects", "Snails"],
  "Salt marsh, mudflats, mangroves, and shallow freshwater wetlands."),

S("Green Heron", "Butorides virescens", "Pelecaniformes", "🐦", ["waterfowl"],
  "41–46 cm", "240 g", "64–68 cm", "~7 yr",
  "NE:u55 SE:c65 MW:u55 NW:u45 SW:u40 CA:u50 TX:c60",
  "One of the very few tool-using birds — it drops feathers, twigs, or insects onto the water as bait and waits for fish to rise. Compact, secretive, and easy to miss until it barks its sharp alarm call.",
  "Deep chestnut neck, dark iridescent green-blue back, a shaggy dark crown, and orange-yellow legs.",
  "Very similar to the male, typically a little duller with less intense leg color outside breeding season.",
  ["Small fish", "Frogs", "Crayfish", "Aquatic insects"],
  "Wooded swamps, stream edges, and pond margins with overhanging cover. Hunts from the water's edge."),

S("Black-crowned Night-Heron", "Nycticorax nycticorax", "Pelecaniformes", "🐦", ["waterfowl"],
  "58–66 cm", "0.7–1 kg", "112–118 cm", "~21 yr",
  "NE:u55 SE:c65 MW:u55 NW:u50 SW:u55 CA:c65 TX:c65",
  "A stocky, hunched heron that hunts mostly at dusk and after dark, when the day-herons have gone to roost — neatly sidestepping competition. Roosts communally in dense trees by day.",
  "Black crown and back, pale grey wings, white underparts, and startling red eyes. Two long white head plumes when breeding.",
  "Identical to the male in plumage, slightly smaller.",
  ["Fish", "Crustaceans", "Amphibians", "Insects", "Eggs"],
  "Marshes, wooded swamps, and pond edges. Roosts by day in dense trees near water."),

S("Sandhill Crane", "Antigone canadensis", "Gruiformes", "🐦", ["waterfowl"],
  "100–120 cm", "3–6.5 kg", "180–210 cm", "~20 yr",
  "NE:u45 SE:u50 MW:c70 NW:u55 SW:u50 CA:u55 TX:c65",
  "Among the oldest surviving bird species on Earth — a fossil from Nebraska matches the modern bird and is about ten million years old. The bugling call carries for miles, and migrating flocks stage in the hundreds of thousands.",
  "Tall grey body, bright red crown of bare skin, and a bustle of drooping feathers over the rump. Often stained rusty from preening with iron-rich mud.",
  "Identical to the male. Pairs mate for life and perform elaborate leaping courtship dances together.",
  ["Grain", "Tubers", "Insects", "Small vertebrates", "Berries"],
  "Wet meadows, marshes, and prairie for breeding; harvested grain fields and river roosts on migration."),

S("American Coot", "Fulica americana", "Gruiformes", "🐦", ["waterfowl"],
  "34–43 cm", "430–850 g", "58–71 cm", "~9 yr",
  "NE:c75 SE:c80 MW:c75 NW:c75 SW:c75 CA:c88 TX:c80",
  "Not a duck at all but a rail, with lobed toes instead of webbed feet. Runs splashily across the water to take off, and squabbles constantly in winter flocks.",
  "Slate-grey to black body with a bright white chicken-like bill and a red eye. Greenish lobed feet.",
  "Identical to the male. Both sexes aggressively defend territory with charging, splashing displays.",
  ["Aquatic plants", "Algae", "Insects", "Tadpoles", "Seeds"],
  "Ponds, marshes, lakes, and reservoirs with open water and emergent vegetation. Often grazes on lawns nearby."),

S("Pied-billed Grebe", "Podilymbus podiceps", "Podicipediformes", "🐦", ["waterfowl"],
  "31–38 cm", "250–570 g", "45–62 cm", "~10 yr",
  "NE:c65 SE:c70 MW:c65 NW:c65 SW:c65 CA:c70 TX:c70",
  "A stubby, secretive grebe that would rather sink slowly out of sight than fly. It can control its buoyancy by trapping or releasing air in its feathers, submerging like a submarine.",
  "Brown overall with a black throat patch and a thick pale bill crossed by a black ring in breeding season.",
  "Identical to the male. Both lose the bill ring and throat patch in winter, becoming plain buffy brown.",
  ["Crayfish", "Small fish", "Aquatic insects", "Amphibians"],
  "Ponds, marshes, and slow rivers with dense emergent vegetation to hide in."),

S("Double-crested Cormorant", "Nannopterum auritum", "Suliformes", "🐦", ["waterfowl"],
  "70–90 cm", "1.2–2.5 kg", "114–123 cm", "~6 yr",
  "NE:c80 SE:c80 MW:c75 NW:c80 SW:u60 CA:c80 TX:c75",
  "Its feathers are deliberately wettable, which cuts buoyancy and makes it a superb underwater pursuit diver — but it must then stand with wings spread to dry, the classic cormorant pose.",
  "All black with a hooked bill and a patch of bare orange skin at the throat. Iridescent green sheen in good light.",
  "Identical to the male. The paired head tufts that give the bird its name are only briefly present in breeding season.",
  ["Fish", "Amphibians", "Crustaceans"],
  "Lakes, rivers, reservoirs, and coasts. Nests colonially in trees or on rocky islands."),

S("American White Pelican", "Pelecanus erythrorhynchos", "Pelecaniformes", "🐦", ["waterfowl"],
  "127–165 cm", "4.5–9 kg", "244–290 cm", "~16 yr",
  "MW:u55 NW:u55 SW:u55 CA:c65 TX:c70 SE:u55",
  "One of the largest birds in North America, with a wingspan approaching nine feet. Unlike Brown Pelicans it never plunge-dives — instead, groups herd fish cooperatively into the shallows and scoop them up together.",
  "Enormous white bird with black flight feathers and a huge orange bill and pouch. Grows a strange horn on the bill when breeding.",
  "Identical to the male, including the breeding bill horn, which is shed after eggs are laid.",
  ["Fish", "Crayfish", "Amphibians"],
  "Large lakes, reservoirs, and coastal lagoons. Breeds on isolated islands in prairie and western lakes."),

S("Brown Pelican", "Pelecanus occidentalis", "Pelecaniformes", "🐦", ["waterfowl"],
  "100–137 cm", "2–5 kg", "203–228 cm", "~15 yr",
  "SE:c80 CA:c80 TX:c80",
  "A DDT casualty that came all the way back from the brink. Plunge-dives from height, hitting the water hard enough that air sacs under its skin cushion the impact.",
  "Grey-brown body with a white head washed yellow. In breeding plumage the hindneck turns deep chestnut.",
  "Identical to the male. Both sexes feed young by regurgitation into the enormous pouch.",
  ["Fish (chiefly menhaden and anchovies)"],
  "Coastal waters, bays, and estuaries. Almost never inland. Roosts on sandbars, pilings, and jetties."),

S("Killdeer", "Charadrius vociferus", "Charadriiformes", "🐦", ["waterfowl"],
  "23–28 cm", "72–128 g", "59–63 cm", "~5 yr",
  "NE:c82 SE:c82 MW:c85 NW:c85 SW:c80 CA:c85 TX:c85",
  "Famous for the broken-wing act — it drags a 'crippled' wing away from the nest until the predator follows, then flies off perfectly fine. Nests on bare gravel, including parking lots and flat roofs.",
  "Brown above, white below, with two crisp black breast bands and a rusty rump that flashes in flight.",
  "Identical to the male. Both parents perform the distraction display, though only the female incubates.",
  ["Earthworms", "Beetles", "Grasshoppers", "Snails"],
  "Open bare ground of any kind — gravel lots, airports, farm fields, shorelines, and playing fields."),

S("Spotted Sandpiper", "Actitis macularius", "Charadriiformes", "🐦", ["waterfowl"],
  "18–20 cm", "34–50 g", "37–40 cm", "~12 yr",
  "NE:c70 SE:u60 MW:c70 NW:c75 SW:u60 CA:c70 TX:u60",
  "Teeters its rear end constantly, as if perpetually off balance. Unusually, the female is the aggressor — she arrives first, defends the territory, and may leave several males to raise her broods.",
  "Bold dark spots on a white breast in summer; plain white below in winter. Constant bobbing motion and stiff, fluttery wingbeats.",
  "Same spotted plumage but often more heavily marked than the male. She mates with several males in a season.",
  ["Insects", "Small crustaceans", "Worms"],
  "Edges of almost any freshwater — streams, ponds, lakeshores — and coastal shorelines in migration."),

S("Ring-billed Gull", "Larus delawarensis", "Charadriiformes", "🐦", ["waterfowl"],
  "43–54 cm", "300–700 g", "105–117 cm", "~20 yr",
  "NE:c88 SE:c80 MW:c88 NW:c80 SW:u60 CA:c80 TX:c75",
  "The quintessential parking-lot gull — abundant, bold, and thoroughly at home around people. Often the gull begging for fries a hundred miles from any coast.",
  "White head and body, pale grey back, and a yellow bill crossed by a neat black ring. Yellow legs.",
  "Identical to the male. Takes three years to reach full adult plumage, so mottled brown youngsters are common.",
  ["Fish", "Insects", "Grain", "Refuse", "Earthworms"],
  "Lakes, rivers, coasts, landfills, parking lots, and farm fields. Extremely adaptable."),

S("Herring Gull", "Larus argentatus", "Charadriiformes", "🐦", ["waterfowl"],
  "55–66 cm", "0.8–1.5 kg", "135–145 cm", "~30 yr",
  "NE:c80 SE:c70 MW:c65 NW:u55 CA:u55 TX:u55",
  "The archetypal 'seagull' of the North Atlantic. Highly intelligent — known to drop clams onto rocks and pavement to crack them, and to stamp on wet sand to imitate rain and bring worms up.",
  "White head and body, grey back, black wingtips with white spots, and a heavy yellow bill with a red spot near the tip.",
  "Identical to the male. Takes four years to mature, passing through a confusing series of mottled brown plumages.",
  ["Fish", "Crabs", "Refuse", "Eggs", "Carrion"],
  "Coasts, harbors, large lakes, and landfills. Nests colonially on islands and rooftops."),


# ══════════════════════════════════════════════════════════════════
# GAMEBIRDS
# ══════════════════════════════════════════════════════════════════

S("Wild Turkey", "Meleagris gallopavo", "Galliformes", "🦃", ["songbird"],
  "76–125 cm", "2.5–11 kg", "144–180 cm", "~5 yr",
  "NE:c75 SE:c80 MW:c75 NW:u60 SW:u55 CA:u60 TX:c75",
  "Nearly extirpated by 1900, then restored by one of the great wildlife comebacks — trap-and-transfer programs put them back across the continent. Can run 25 mph and fly, briefly, at 55.",
  "Iridescent bronze body, bare red-and-blue head with wattles and a fleshy snood, and a bristly 'beard' on the chest. Fans the tail in display.",
  "Smaller, duller, and browner, with a bluish bare head and usually no beard. Far more cryptic than the male.",
  ["Acorns", "Seeds", "Insects", "Berries", "Small vertebrates"],
  "Mature forest next to clearings and fields. Forages on the ground; roosts in big trees at night."),

S("Northern Bobwhite", "Colinus virginianus", "Galliformes", "🐦", ["songbird"],
  "24–28 cm", "170 g", "33 cm", "~1.5 yr",
  "NE:r15 SE:u50 MW:u40 TX:u55",
  "The whistled 'bob-WHITE!' was once the sound of every farm hedgerow in the East. Modern agriculture erased the weedy edges it needs, and the species has collapsed across most of its former range.",
  "Warm rufous-brown with an intricate black-and-white head — bold white eyebrow and throat outlined in black.",
  "Same pattern but with buff replacing the white on the face and throat, giving a warmer, softer look.",
  ["Seeds", "Insects", "Berries", "Leaves"],
  "Weedy field edges, brushy fencerows, and pine savanna. Needs dense low cover for nesting and roosting."),

S("Ring-necked Pheasant", "Phasianus colchicus", "Galliformes", "🐦", ["songbird"],
  "50–89 cm", "0.5–1.4 kg", "56–86 cm", "~3 yr",
  "NE:u50 MW:c65 NW:u55 CA:u50 TX:u45",
  "An Asian import, released for hunting since the 1880s and now thoroughly naturalized across the northern farm belt. The male's crowing and explosive, clattering flush are unmistakable.",
  "Spectacular copper body flecked with black, an iridescent green head, bold red face wattles, a white neck ring, and an enormously long pointed tail.",
  "Mottled buff-brown throughout with a shorter pointed tail — beautifully camouflaged against stubble and grass.",
  ["Seeds", "Grain", "Insects", "Berries", "Roots"],
  "Farmland with weedy ditches, hedgerows, and grassy cover. Depends on agricultural landscapes."),

S("California Quail", "Callipepla californica", "Galliformes", "🐦", ["songbird"],
  "24–27 cm", "140–230 g", "32–37 cm", "~2 yr",
  "CA:c85 NW:c65 SW:u50",
  "California's state bird, moving in chatty coveys that can number over a hundred in winter. The forward-curling topknot looks like a single feather but is actually six overlapping ones.",
  "Grey and brown with a scaled belly, a black face bordered in white, and a comma-shaped black topknot.",
  "Softer grey-brown with a smaller topknot and no black face pattern. Same scaled belly.",
  ["Seeds", "Leaves", "Berries", "Insects"],
  "Chaparral, oak woodland edges, brushy foothills, parks, and suburban gardens with cover."),

S("Gambel's Quail", "Callipepla gambelii", "Galliformes", "🐦", ["songbird"],
  "24–29 cm", "160–200 g", "33–36 cm", "~2 yr",
  "SW:c80 CA:u45 TX:u45",
  "The desert counterpart to the California Quail, running rather than flying between creosote bushes. Its breeding success is tied tightly to winter rainfall — dry years mean almost no chicks.",
  "Grey body with rich chestnut flanks streaked white, a black face and bib, a chestnut cap, and a teardrop topknot. Black belly patch.",
  "Plain grey-brown with a small topknot and no black face — but the same chestnut flanks.",
  ["Seeds", "Cactus fruit", "Leaves", "Insects"],
  "Desert scrub, mesquite thickets, and washes in the Sonoran and Mojave. Needs a reliable water source."),
