# ══════════════════════════════════════════════════════════════════
# CHICKADEES · TITMICE · NUTHATCHES · WRENS · KINGLETS
# ══════════════════════════════════════════════════════════════════

S("Black-capped Chickadee", "Poecile atricapillus", "Passeriformes", "🐦", ["songbird"],
  "12–15 cm", "9–14 g", "16–21 cm", "~12 yr",
  "NE:c97 MW:c92 NW:c88",
  "Every autumn it grows new brain cells in the hippocampus to store the locations of thousands of hidden seeds, then shrinks it back in spring. The 'chick-a-dee' call encodes threat level — more 'dee's means a more dangerous predator.",
  "Black cap and bib, crisp white cheeks, grey back, and buff-washed flanks.",
  "Identical to the male. The whistled 'fee-bee' song is given mostly by males.",
  ["Insects", "Seeds", "Berries", "Suet", "Spider eggs"],
  "Woodlands, thickets, parks, and wooded suburbs. The nucleus of winter mixed-species flocks."),

S("Carolina Chickadee", "Poecile carolinensis", "Passeriformes", "🐦", ["songbird"],
  "11–13 cm", "8–12 g", "15–20 cm", "~11 yr",
  "SE:c92 TX:c80 MW:u55",
  "The southern counterpart to the Black-capped, nearly identical to look at. Where their ranges meet they hybridize along a narrow band that has been creeping north with warming winters.",
  "Black cap and bib with white cheeks — like a Black-capped but slightly smaller, with a crisper bib edge and less white in the wing.",
  "Identical to the male. Best separated from Black-capped by its faster four-note song.",
  ["Insects", "Seeds", "Berries", "Suet"],
  "Deciduous woods, swamps, parks, and suburbs across the Southeast."),

S("Tufted Titmouse", "Baeolophus bicolor", "Passeriformes", "🐦", ["songbird"],
  "14–16 cm", "18–26 g", "23–28 cm", "~2 yr avg",
  "NE:c88 SE:c88 MW:c85 TX:c75",
  "Plucks hair directly from living animals to line its nest — squirrels, dogs, and occasionally unsuspecting humans. Its clear whistled 'PETER-peter-peter' is one of the definitive sounds of eastern woods.",
  "Soft grey above, white below with rusty flanks, a pointed grey crest, and a black patch above the bill.",
  "Identical to the male. Young often stay with the parents through the winter.",
  ["Seeds", "Insects", "Acorns", "Sunflower seeds", "Suet"],
  "Deciduous woodland, parks, and suburbs with mature trees. Dominant at feeders."),

S("White-breasted Nuthatch", "Sitta carolinensis", "Passeriformes", "🐦", ["songbird"],
  "13–14 cm", "18–30 g", "22–27 cm", "~2 yr avg",
  "NE:c88 SE:c85 MW:c88 NW:c70 SW:u60 CA:c70 TX:c70",
  "The upside-down bird — it's the only group that routinely walks head-first down tree trunks, which lets it spot insects that woodpeckers moving upward miss entirely. Wedges nuts into bark and hammers them open, hence 'nut-hatch'.",
  "Blue-grey above, white face and breast, a black cap, and rusty undertail. Stubby tail, long bill.",
  "Very similar, but the cap is grey rather than glossy black — visible when a pair is together.",
  ["Insects", "Acorns", "Sunflower seeds", "Suet"],
  "Mature deciduous and mixed forest, parks, and wooded suburbs. Joins chickadee flocks in winter."),

S("Red-breasted Nuthatch", "Sitta canadensis", "Passeriformes", "🐦", ["songbird"],
  "11–12 cm", "9–13 g", "20–22 cm", "~7 yr",
  "NE:u55 NW:c75 CA:u55 MW:u50 SW:u50",
  "Smears sticky conifer resin around its nest hole — possibly to deter predators and insects — and then must dive through the gap without touching the sides. In poor cone years it 'irrupts' far south of its normal range.",
  "Blue-grey above, rusty-orange below, with a black cap and a bold white eyebrow over a black eye-line.",
  "Same pattern but with a grey cap and paler, buffier underparts.",
  ["Conifer seeds", "Insects", "Suet", "Sunflower seeds"],
  "Coniferous and mixed forest. Wanders widely into deciduous woods and feeders during irruption years."),

S("Brown Creeper", "Certhia americana", "Passeriformes", "🐦", ["songbird"],
  "12–14 cm", "7–10 g", "17–20 cm", "~4 yr",
  "NE:u55 SE:u45 MW:u55 NW:c60 CA:u55",
  "Spirals up a trunk from the base, then drops to the bottom of the next tree and starts again. So perfectly bark-camouflaged that it often goes unnoticed until it moves. Roosts tucked behind a slab of loose bark.",
  "Streaky brown above and silvery-white below, with a thin decurved bill and a stiff tail used as a prop.",
  "Identical to the male. Its high, thin song is at the very top of human hearing.",
  ["Insects", "Spiders", "Larvae hidden in bark"],
  "Mature forest with big rough-barked trees. Needs loose bark for its hammock-shaped nest."),

S("Carolina Wren", "Thryothorus ludovicianus", "Passeriformes", "🐦", ["songbird"],
  "12–14 cm", "18–22 g", "29 cm", "~6 yr",
  "NE:c70 SE:c88 MW:c65 TX:c75",
  "One of the loudest birds in North America for its size — the song carries half a mile. Pairs stay together year-round and duet. Hard winters with deep snow can crash the population overnight.",
  "Rich rufous above, warm buff below, with a bold white eyebrow and a cocked tail.",
  "Identical to the male, though only he sings the full ringing 'tea-kettle tea-kettle' song.",
  ["Insects", "Spiders", "Berries", "Suet"],
  "Brushy tangles, woodland understory, brush piles, and shrubby gardens. Nests in almost any cavity or crevice."),

S("House Wren", "Troglodytes aedon", "Passeriformes", "🐦", ["songbird"],
  "11–13 cm", "10–12 g", "15 cm", "~7 yr",
  "NE:c78 SE:u55 MW:c80 NW:c70 SW:u60 CA:c65 TX:u55",
  "Tiny, brown, and utterly ferocious — it will pierce the eggs of any bird nesting nearby, including other wrens, to clear the neighborhood of competitors. Males build several dummy nests for the female to choose from.",
  "Small, plain grey-brown with fine barring on the wings and tail, a faint eyebrow, and a frequently cocked tail.",
  "Identical to the male. She picks one of his dummy nests and finishes it herself.",
  ["Insects", "Spiders", "Caterpillars", "Beetles"],
  "Thickets, brushy edges, gardens, and backyards. Uses nest boxes, old boots, mailboxes — almost any cavity."),

S("Bewick's Wren", "Thryomanes bewickii", "Passeriformes", "🐦", ["songbird"],
  "13–14 cm", "8–12 g", "18 cm", "~8 yr",
  "CA:c75 NW:c65 SW:c65 TX:c65",
  "Has vanished almost entirely from east of the Mississippi, likely pushed out by House Wrens, but remains common in the West. Waves its long tail from side to side rather than cocking it up.",
  "Grey-brown above, clean white-grey below, with a long white eyebrow and a long tail edged with white spots.",
  "Identical to the male. Males learn their song from neighbors, producing local dialects.",
  ["Insects", "Spiders", "Larvae"],
  "Chaparral, scrub, brush piles, thickets, and suburban gardens with dense cover."),

S("Golden-crowned Kinglet", "Regulus satrapa", "Passeriformes", "🐦", ["songbird"],
  "8–11 cm", "4–8 g", "14–18 cm", "~6 yr",
  "NE:u60 SE:u50 MW:u55 NW:c70 CA:u55",
  "Weighs about as much as two pennies yet survives nights of −40°F in boreal forest, huddling together and shivering all night long. Constantly flicking its wings as it forages.",
  "Tiny olive-grey bird with a black-bordered crown stripe that is flaming orange in the center.",
  "Identical but the crown stripe is pure lemon-yellow with no orange.",
  ["Tiny insects", "Springtails", "Spider eggs", "Aphids"],
  "Coniferous forest, especially spruce and fir. Spreads into mixed woods and suburbs in winter."),

S("Ruby-crowned Kinglet", "Corthylio calendula", "Passeriformes", "🐦", ["songbird"],
  "9–11 cm", "5–10 g", "16–18 cm", "~5 yr",
  "NE:u60 SE:c65 MW:u60 NW:c70 SW:u60 CA:c70 TX:c65",
  "A frantic scrap of a bird, never still, and possessed of a song wildly out of proportion to its size — loud, rich, and tumbling. The male's red crown is hidden until he gets excited, then it flares like a struck match.",
  "Drab olive with two white wingbars, a broken white eye-ring, and a scarlet crown patch usually kept concealed.",
  "Identical but with no red crown at all. Both flick their wings constantly.",
  ["Tiny insects", "Spiders", "Aphids", "Berries"],
  "Conifers in summer; nearly any woodland, thicket, or garden on migration and in winter."),

S("Blue-gray Gnatcatcher", "Polioptila caerulea", "Passeriformes", "🐦", ["songbird"],
  "10–13 cm", "5–7 g", "16 cm", "~4 yr",
  "NE:u55 SE:c70 MW:u55 SW:u60 CA:u60 TX:c70",
  "Builds an exquisite nest of plant down bound with spider silk and shingled with lichen, so well camouflaged it looks like a knot on the branch. Never stops moving or flicking its long tail.",
  "Tiny, slim, blue-grey above and white below, with a white eye-ring and a long black tail edged in white. Thin black eyebrow when breeding.",
  "Similar but greyer and lacking the black eyebrow.",
  ["Small insects", "Spiders", "Larvae"],
  "Open deciduous woodland, oak scrub, and woodland edges."),


# ══════════════════════════════════════════════════════════════════
# SWALLOWS · MARTINS
# ══════════════════════════════════════════════════════════════════

S("Barn Swallow", "Hirundo rustica", "Passeriformes", "🐦", ["songbird"],
  "15–19 cm", "17–20 g", "28–33 cm", "~4 yr",
  "NE:c82 SE:c80 MW:c85 NW:c80 SW:c75 CA:c80 TX:c80",
  "The most widespread swallow on Earth, and one of the most thoroughly tied to us — it has almost entirely abandoned caves and cliffs in favor of barns, bridges, and culverts.",
  "Deep steel-blue above, rusty-orange throat, buff underparts, and a long deeply forked tail with white spots.",
  "Same pattern but with shorter tail streamers and paler underparts. Males with the longest tails get the best mates.",
  ["Flying insects", "Flies", "Beetles", "Mosquitoes"],
  "Open country near water — farms, fields, and marshes. Nests almost exclusively on human structures."),

S("Tree Swallow", "Tachycineta bicolor", "Passeriformes", "🐦", ["songbird"],
  "12–14 cm", "16–25 g", "30–35 cm", "~12 yr",
  "NE:c80 SE:u60 MW:c80 NW:c75 SW:u55 CA:c70 TX:u55",
  "Unlike other swallows it can digest berries, especially bayberry, which lets it winter further north than any of its relatives and arrive back earliest in spring.",
  "Iridescent blue-green above, clean white below, with a sharp line through the eye. Dazzling in sunlight.",
  "Similar but often duller and browner — first-year females can be almost entirely brown above.",
  ["Flying insects", "Bayberries", "Beetles"],
  "Open fields, marshes, and lakeshores. A cavity nester that took eagerly to bluebird boxes."),

S("Purple Martin", "Progne subis", "Passeriformes", "🐦", ["songbird"],
  "19–20 cm", "45–60 g", "39–41 cm", "~13 yr",
  "NE:u60 SE:c75 MW:c70 TX:c70 NW:r30",
  "East of the Rockies, Purple Martins nest almost exclusively in human-supplied housing — a relationship that goes back to Indigenous peoples hanging hollow gourds. The eastern population is now entirely dependent on us.",
  "Glossy deep blue-purple all over — the only North American swallow with a dark belly.",
  "Grey-brown below with a pale collar and a duller, sooty-blue back.",
  ["Flying insects", "Dragonflies", "Beetles", "Flies"],
  "Open areas near water, especially around martin houses and gourd racks in towns and farms."),


# ══════════════════════════════════════════════════════════════════
# THRUSHES · MIMIDS · WAXWINGS · STARLINGS
# ══════════════════════════════════════════════════════════════════

S("Eastern Bluebird", "Sialia sialis", "Passeriformes", "🐦", ["songbird"],
  "16–21 cm", "27–34 g", "25–32 cm", "6–10 yr",
  "NE:c65 SE:c78 MW:c68 TX:c70",
  "Nearly lost to competition from introduced starlings and House Sparrows, then rescued by an army of volunteers who put up hundreds of thousands of nest boxes along 'bluebird trails'. One of conservation's quiet triumphs.",
  "Vivid royal blue above with a rich rusty-orange throat and breast and a white belly.",
  "Softer grey-blue above with a paler orange breast and a white eye-ring. Blue shows brightest in the wings and tail.",
  ["Insects", "Caterpillars", "Berries", "Mealworms"],
  "Open country with scattered trees — pastures, orchards, golf courses, and roadsides. Depends on nest boxes."),

S("Western Bluebird", "Sialia mexicana", "Passeriformes", "🐦", ["songbird"],
  "15–18 cm", "24–31 g", "29–34 cm", "~8 yr",
  "CA:c75 NW:c70 SW:c65",
  "The western counterpart of the Eastern Bluebird, and equally dependent on cavities. Family groups often stay together, with older offspring helping to feed the next brood.",
  "Deep blue head, throat, wings and tail, with a chestnut breast and often a chestnut patch on the upper back.",
  "Grey-buff with a blue wash in the wings and tail and a dull orange breast.",
  ["Insects", "Berries", "Mistletoe", "Caterpillars"],
  "Open oak and pine woodland, burned forest, orchards, and rangeland with snags."),

S("American Robin", "Turdus migratorius", "Passeriformes", "🐦", ["songbird"],
  "23–28 cm", "72–94 g", "31–41 cm", "~2 yr avg",
  "NE:c97 SE:c90 MW:c97 NW:c95 SW:c85 CA:c95 TX:c88",
  "Everyone's first bird. It doesn't actually leave in winter so much as change behavior — flocking into woods to eat fruit, then returning to lawns when the ground thaws, which is why it seems to 'arrive' each spring.",
  "Dark grey-black head and back, brick-orange breast, white eye-arcs, and a yellow bill.",
  "Paler and browner overall, with a duller orange breast and a greyer head. Obvious when a pair is side by side.",
  ["Earthworms", "Insects", "Berries", "Fruit"],
  "Lawns, parks, gardens, forests, and tundra alike — one of the most adaptable birds on the continent."),

S("Hermit Thrush", "Catharus guttatus", "Passeriformes", "🐦", ["songbird"],
  "15–18 cm", "18–37 g", "25–29 cm", "~8 yr",
  "NE:u60 SE:u60 MW:u55 NW:c65 CA:c65 SW:u55",
  "Sings what many consider the most beautiful song of any North American bird — a clear flute-like phrase, repeated at a different pitch each time. It can sing two notes at once using both halves of its syrinx.",
  "Warm brown above with a rusty tail it flicks upward, a spotted breast, and a bold white eye-ring.",
  "Identical to the male. The rusty tail contrasting with the browner back is the key mark.",
  ["Insects", "Berries", "Ants", "Beetles"],
  "Coniferous and mixed forest floor in summer; woodland understory and thickets in winter."),

S("Wood Thrush", "Hylocichla mustelina", "Passeriformes", "🐦", ["songbird"],
  "18–21 cm", "40–50 g", "30–40 cm", "~8 yr",
  "NE:c65 SE:c65 MW:u55",
  "Its ethereal, fluting 'ee-oh-lay' is the signature sound of the eastern summer forest. Populations have fallen by more than half since 1970, hit from both ends by forest fragmentation here and deforestation in Central America.",
  "Warm rusty-brown head and back fading to olive, with a white breast boldly marked in large black spots.",
  "Identical to the male. Both sing, but only the male gives the full song.",
  ["Insects", "Beetles", "Berries", "Snails"],
  "Interior deciduous forest with a moist shaded understory. Needs large unbroken woods."),

S("Gray Catbird", "Dumetella carolinensis", "Passeriformes", "🐦", ["songbird"],
  "20–24 cm", "23–56 g", "22–30 cm", "~11 yr",
  "NE:c75 SE:c75 MW:c75 NW:u50 TX:u55",
  "Named for its cat-like mew. A gifted mimic and improviser — unlike a mockingbird it rarely repeats a phrase, instead stringing together a long, rambling, ever-changing performance from deep inside a thicket.",
  "Uniform slate-grey with a black cap and a chestnut patch beneath the tail.",
  "Identical to the male. Neither sex can be told apart in the field.",
  ["Insects", "Berries", "Fruit", "Ants"],
  "Dense thickets, hedgerows, and shrubby gardens. Skulking, but responds readily to pishing."),

S("Northern Mockingbird", "Mimus polyglottos", "Passeriformes", "🐦", ["songbird"],
  "21–26 cm", "45–58 g", "31–35 cm", "~8 yr",
  "NE:c65 SE:c92 MW:c65 SW:c80 CA:c80 TX:c92",
  "Can learn 200 songs in a lifetime, imitating other birds, frogs, car alarms, and squeaky gates. Unmated males sing through the night, often from a streetlight, to the despair of anyone trying to sleep.",
  "Grey above, pale below, with two white wingbars and huge white wing patches that flash in flight.",
  "Identical to the male. Both sexes aggressively defend territory, dive-bombing cats and people alike.",
  ["Insects", "Berries", "Fruit", "Earthworms"],
  "Suburbs, parks, hedgerows, and open country with scattered shrubs. Thrives around people."),

S("Brown Thrasher", "Toxostoma rufum", "Passeriformes", "🐦", ["songbird"],
  "23–30 cm", "61–89 g", "29–33 cm", "~12 yr",
  "NE:c62 SE:c70 MW:c65 TX:c60",
  "Holds the largest song repertoire of any North American bird — over 1,100 song types. Unlike the mockingbird, which repeats each phrase three or more times, the thrasher usually sings each one twice.",
  "Rich rufous above with a heavily black-streaked white breast, a long curved bill, and staring yellow eyes.",
  "Identical to the male. Both thrash through leaf litter with the bill, hence the name.",
  ["Beetles", "Earthworms", "Berries", "Acorns"],
  "Dense thickets, hedgerows, and shrubby field edges. Sings from an exposed high perch."),

S("Cedar Waxwing", "Bombycilla cedrorum", "Passeriformes", "🐦", ["songbird"],
  "14–17 cm", "32 g", "22–30 cm", "~8 yr",
  "NE:c72 SE:c70 MW:c72 NW:c70 SW:u55 CA:c70 TX:c65",
  "The most elegant bird at any feeder-less winter berry tree. Flocks pass berries down a line from bird to bird. They occasionally get drunk on fermented fruit and fly into windows.",
  "Silky fawn-grey with a black mask, a jaunty crest, a yellow-tipped tail, and red waxy droplets on the wing.",
  "Nearly identical. The red wing tips increase with age rather than differing by sex.",
  ["Berries", "Fruit", "Serviceberries", "Insects"],
  "Fruiting trees anywhere — woods, parks, orchards, and suburbs. Highly nomadic, following the fruit crop."),

S("European Starling", "Sturnus vulgaris", "Passeriformes", "🐦", ["songbird"],
  "19–23 cm", "58–101 g", "31–44 cm", "2–3 yr",
  "NE:c97 SE:c92 MW:c97 NW:c95 SW:c88 CA:c95 TX:c92",
  "All 200 million North American starlings descend from about 100 birds released in Central Park in the 1890s. A superb mimic, an aggressive cavity competitor that displaces native birds, and the author of the astonishing swirling murmurations of winter.",
  "Winter: blackish and covered in white spots, with a dark bill. Summer: glossy iridescent green-purple with a bright yellow bill.",
  "Same seasonal changes, slightly less glossy. In breeding condition his bill base is blue, hers is pink.",
  ["Insects", "Grain", "Fruit", "Refuse", "Suet"],
  "Cities, farms, suburbs, and fields. Nests in any cavity in any structure."),

S("House Sparrow", "Passer domesticus", "Passeriformes", "🐦", ["songbird"],
  "14–17 cm", "24–39 g", "19–25 cm", "3–5 yr",
  "NE:c97 SE:c92 MW:c97 NW:c92 SW:c90 CA:c92 TX:c92",
  "Introduced to Brooklyn in 1851 and now among the most widespread birds on Earth. It has lived alongside humans since the dawn of agriculture, and is oddly now declining in many cities for reasons nobody fully understands.",
  "Grey crown, chestnut nape, black bib, white cheek, and a streaked brown back. Bib size signals dominance.",
  "Plain dusty brown, streaked above, with a buff eyebrow behind the eye and no bib at all.",
  ["Seeds", "Grain", "Bread", "Insects"],
  "Cities, suburbs, farms, and feedlots. Almost never found away from human settlement."),
