# ══════════════════════════════════════════════════════════════════
# WARBLERS
# ══════════════════════════════════════════════════════════════════

S("Yellow Warbler", "Setophaga petechia", "Passeriformes", "🐦", ["songbird"],
  "10–18 cm", "9–11 g", "16–22 cm", "~10 yr",
  "NE:c72 SE:u55 MW:c72 NW:c75 SW:u60 CA:c70 TX:u55",
  "When a cowbird lays an egg in its nest, the Yellow Warbler simply builds a new floor over it and starts again — nests six stories tall have been found, each layer entombing a cowbird egg.",
  "Brilliant egg-yolk yellow all over, with rusty-red streaks down the breast and large dark eyes on a plain face.",
  "Plain yellow with no streaking and a slightly greenish wash above.",
  ["Caterpillars", "Insects", "Beetles", "Spiders"],
  "Willow and alder thickets along streams, wet shrubby areas, and gardens with dense shrubs."),

S("Yellow-rumped Warbler", "Setophaga coronata", "Passeriformes", "🐦", ["songbird"],
  "12–15 cm", "10–14 g", "19–24 cm", "~7 yr",
  "NE:c75 SE:c80 MW:c72 NW:c78 SW:c70 CA:c80 TX:c75",
  "Nicknamed 'butter-butt'. Uniquely among warblers it can digest the waxes in bayberry and wax myrtle, which lets it winter far north of every other warbler — often the only one you'll see in a northern January.",
  "Blue-grey with black streaking, a yellow crown, yellow side patches, and a bright yellow rump. Eastern birds have a white throat.",
  "Browner and duller but with the same four yellow patches — crown, sides, and rump.",
  ["Insects", "Bayberries", "Wax myrtle", "Berries"],
  "Conifer forest in summer; almost any woodland, thicket, or coastal scrub in winter."),

S("Yellow-throated Warbler", "Setophaga dominica", "Passeriformes", "🐦", ["songbird"],
  "13–14 cm", "9–11 g", "20–23 cm", "~6 yr",
  "SE:c70 NE:u40 TX:u50 MW:u40",
  "Creeps along branches like a nuthatch, probing bark and pine needle clusters. One of the earliest warblers to return north each spring, sometimes in February on the Gulf Coast.",
  "Grey above, with a brilliant yellow throat, a bold black-and-white face pattern, and black side streaks.",
  "Identical to the male, perhaps marginally duller.",
  ["Insects", "Spiders", "Beetles", "Caterpillars"],
  "Pine woods, cypress swamps, and sycamore-lined rivers in the Southeast."),

S("Black-throated Green Warbler", "Setophaga virens", "Passeriformes", "🐦", ["songbird"],
  "11–13 cm", "8–11 g", "17–20 cm", "~7 yr",
  "NE:c65 SE:u50 MW:u50",
  "Sings a drowsy, buzzy 'zee-zee-zee-zoo-zee' that carries through the summer canopy. A male may sing it over 400 times an hour, which is a remarkable amount of enthusiasm for a bird that weighs a third of an ounce.",
  "Bright olive-green crown and back, a vivid yellow face, and a solid black throat and bib.",
  "Similar but with a mottled, incomplete black throat and duller yellow face.",
  ["Caterpillars", "Insects", "Spiders"],
  "Coniferous and mixed forest, especially hemlock. Forages high in the canopy."),

S("Common Yellowthroat", "Geothlypis trichas", "Passeriformes", "🐦", ["songbird"],
  "11–14 cm", "9–10 g", "15–19 cm", "~11 yr",
  "NE:c72 SE:c78 MW:c75 NW:c72 SW:u60 CA:c72 TX:c72",
  "The little masked bandit of the marsh, and one of the most widespread warblers on the continent. Its rolling 'witchety-witchety-witchety' comes from deep in the cattails, and the singer is maddeningly hard to actually see.",
  "Olive above with a bright yellow throat and a bold black bandit's mask edged in white above.",
  "Olive with a yellow throat and no mask at all — plainer, and easy to puzzle over.",
  ["Insects", "Spiders", "Caterpillars", "Beetles"],
  "Marshes, wet thickets, and any dense low vegetation near water. Also drier overgrown fields."),

S("American Redstart", "Setophaga ruticilla", "Passeriformes", "🐦", ["songbird"],
  "11–14 cm", "6–9 g", "16–23 cm", "~10 yr",
  "NE:c70 SE:u55 MW:c68 NW:u50 TX:u50",
  "Flashes its brightly patterned tail open and shut to startle insects into flight, then snatches them mid-air. Constantly in motion, pivoting and fanning — it never seems to sit still for a second.",
  "Glossy black with brilliant orange patches on the wings, tail, and sides. Unmistakable.",
  "Grey and olive with the same pattern picked out in lemon-yellow instead of orange.",
  ["Insects", "Caterpillars", "Berries"],
  "Deciduous second-growth woodland and thickets, especially near water."),

S("Black-and-white Warbler", "Mniotilta varia", "Passeriformes", "🐦", ["songbird"],
  "11–13 cm", "8–15 g", "18–22 cm", "~11 yr",
  "NE:c65 SE:c65 MW:u55 TX:u50",
  "Forages like a nuthatch, creeping up and down and around tree trunks — the only warbler that does. Its song is a thin, squeaky 'weesa-weesa-weesa' like a rusty wheel turning.",
  "Boldly striped black and white from head to tail, with a black throat and cheek.",
  "Same zebra striping but with a white throat and a grey cheek — cleaner, less contrasty.",
  ["Insects", "Beetle larvae", "Caterpillars", "Spiders"],
  "Deciduous and mixed forest. Works along trunks and large limbs rather than in the foliage."),

S("Ovenbird", "Seiurus aurocapilla", "Passeriformes", "🐦", ["songbird"],
  "11–16 cm", "16–28 g", "19–26 cm", "~11 yr",
  "NE:c68 SE:u55 MW:c62",
  "Named for its domed, oven-shaped nest built right on the forest floor. The ringing 'TEACHER-TEACHER-TEACHER' crescendo is one of the loudest sounds in the eastern woods for a bird that looks like a small thrush.",
  "Olive-brown above, boldly spotted below, with a bold white eye-ring and an orange crown stripe bordered in black.",
  "Identical to the male. Walks — rather than hops — along the forest floor.",
  ["Insects", "Ants", "Snails", "Worms"],
  "Interior deciduous forest with an open leaf-littered floor. Needs large unfragmented woods."),


# ══════════════════════════════════════════════════════════════════
# SPARROWS · TOWHEES · JUNCOS
# ══════════════════════════════════════════════════════════════════

S("Eastern Towhee", "Pipilo erythrophthalmus", "Passeriformes", "🐦", ["songbird"],
  "17–23 cm", "33–53 g", "20–30 cm", "~12 yr",
  "NE:c65 SE:c75 MW:c60",
  "A huge, dramatically marked sparrow that forages by kicking backward with both feet at once — a distinctive double-scratch that rustles loudly in the leaf litter. Sings 'drink-your-TEA!'",
  "Black hood, back and tail, with bright rufous sides and a white belly. Staring red eye.",
  "Identical pattern, but with warm brown replacing all the black — much more cryptic.",
  ["Seeds", "Insects", "Berries", "Acorns"],
  "Dense shrubby undergrowth, thickets, and woodland edge with heavy leaf litter."),

S("Spotted Towhee", "Pipilo maculatus", "Passeriformes", "🐦", ["songbird"],
  "17–21 cm", "33–49 g", "28 cm", "~11 yr",
  "NW:c75 CA:c80 SW:c70 MW:u45",
  "The western counterpart of the Eastern Towhee, once lumped with it as a single species. Same double-scratch, same red eye, but heavily spotted with white above.",
  "Black hood and back heavily spotted and streaked with white, with rufous sides and a white belly.",
  "Same pattern with grey-brown replacing the black.",
  ["Seeds", "Insects", "Berries", "Acorns"],
  "Chaparral, thickets, brushy hillsides, and shrubby gardens in the West."),

S("Chipping Sparrow", "Spizella passerina", "Passeriformes", "🐦", ["songbird"],
  "12–15 cm", "11–16 g", "18–22 cm", "~4 yr",
  "NE:c72 SE:c72 MW:c72 NW:c70 SW:c65 CA:c70 TX:c65",
  "A trim, tidy little sparrow of lawns and park edges. It historically lined its nest with horsehair, and now makes do with pet fur, string, and whatever fine fibers it can find.",
  "Bright rufous cap, a crisp white eyebrow over a black eye-line, and a clean grey unstreaked breast.",
  "Identical to the male. In winter the cap dulls to streaky brown and the bird becomes far less distinctive.",
  ["Seeds", "Grass seeds", "Insects"],
  "Open woodland, parks, lawns, and suburbs — especially short grass with trees nearby."),

S("Field Sparrow", "Spizella pusilla", "Passeriformes", "🐦", ["songbird"],
  "12–15 cm", "10–14 g", "18–21 cm", "~3 yr",
  "NE:c65 SE:c65 MW:c65 TX:u50",
  "Its song is a series of sweet, sad whistles that accelerate into a trill — often compared to a ping-pong ball dropped on a table. Disappearing as old fields are developed or replanted.",
  "Rusty cap, a plain grey face with a rufous eye-line, a white eye-ring, and a distinctive bright pink bill.",
  "Identical to the male. The pink bill is the giveaway for both sexes.",
  ["Seeds", "Grass seeds", "Insects"],
  "Overgrown fields, brushy pastures, and young second growth. Needs shrubby early-successional habitat."),

S("Song Sparrow", "Melospiza melodia", "Passeriformes", "🐦", ["songbird"],
  "11–18 cm", "17–49 g", "18–24 cm", "~9 yr",
  "NE:c88 SE:c72 MW:c85 NW:c88 SW:u60 CA:c85 TX:u60",
  "One of the most variable birds in North America, with over 50 named subspecies — pale and small in the desert, huge and dark in the Aleutians. Often the first bird singing on a warm February morning.",
  "Streaky brown above and below, with the breast streaks converging into a bold central spot. Rusty crown stripes.",
  "Identical to the male. Both are best identified by the central breast spot and the pumping tail in flight.",
  ["Seeds", "Insects", "Berries", "Beetles"],
  "Brushy areas near water — marsh edges, streamsides, thickets, hedgerows, and gardens."),

S("Swamp Sparrow", "Melospiza georgiana", "Passeriformes", "🐦", ["songbird"],
  "12–15 cm", "15–23 g", "18–19 cm", "~6 yr",
  "NE:c58 SE:c60 MW:c55",
  "Wetland specialist with unusually long legs for a sparrow, letting it wade in shallow water and pick invertebrates from the surface — a niche no other sparrow occupies.",
  "Rich rufous cap, a plain grey face, a white throat, and rusty wings. Overall the most colorful of the streaky sparrows.",
  "Very similar, often with a more streaked crown and slightly duller tones.",
  ["Seeds", "Aquatic invertebrates", "Insects", "Spiders"],
  "Cattail marshes, sedge meadows, and wet shrubby areas. Rarely far from water."),

S("White-throated Sparrow", "Zonotrichia albicollis", "Passeriformes", "🐦", ["songbird"],
  "15–19 cm", "22–32 g", "20–23 cm", "~10 yr",
  "NE:c80 SE:c80 MW:c78 TX:u55",
  "Whistles a clear, plaintive 'Oh-sweet-Canada-Canada' that is the sound of the northern woods. Comes in two permanent morphs — white-striped and tan-striped — and, oddly, each almost always mates with the opposite type.",
  "Bold black-and-white striped crown, a crisp white throat patch, and a bright yellow spot between eye and bill.",
  "Same pattern; the tan-striped morph is duller in both sexes, so morph matters more than sex.",
  ["Seeds", "Berries", "Insects", "Millet"],
  "Forest understory, thickets, and brushy edges. Very common under winter feeders in the East."),

S("White-crowned Sparrow", "Zonotrichia leucophrys", "Passeriformes", "🐦", ["songbird"],
  "16–17 cm", "25–28 g", "21–24 cm", "~13 yr",
  "NW:c75 CA:c85 SW:c75 MW:c65 TX:c65 NE:u50 SE:u55",
  "Young males learn their song dialect from neighbors, producing local accents that differ from valley to valley. Migrating birds can stay awake and flying for two weeks straight.",
  "Bold black-and-white striped crown, a clean grey face and breast, and a bright pinkish-orange bill.",
  "Identical to the male. First-year birds have rusty-brown and tan crown stripes instead of black and white.",
  ["Seeds", "Grasses", "Berries", "Insects"],
  "Brushy fields, hedgerows, chaparral, and gardens. Abundant in the West in winter."),

S("Dark-eyed Junco", "Junco hyemalis", "Passeriformes", "🐦", ["songbird"],
  "13–17 cm", "18–30 g", "18–25 cm", "~11 yr",
  "NE:c85 SE:c80 MW:c85 NW:c85 SW:c75 CA:c80 TX:c70",
  "The 'snowbird' that shows up under feeders the week the weather turns. Comes in strikingly different regional forms — slate-grey in the East, boldly black-and-rust in the Rockies — that were once considered separate species.",
  "Eastern form: slate-grey hood, back and breast with a clean white belly, a pink bill, and white outer tail feathers that flash in flight.",
  "Similar but browner and paler grey, with the same pink bill and white tail flashes.",
  ["Seeds", "Millet", "Insects", "Berries"],
  "Coniferous and mixed forest in summer; feeders, thickets, and woodland edge in winter."),


# ══════════════════════════════════════════════════════════════════
# CARDINALS · GROSBEAKS · BUNTINGS · TANAGERS
# ══════════════════════════════════════════════════════════════════

S("Northern Cardinal", "Cardinalis cardinalis", "Passeriformes", "🐦", ["songbird"],
  "21–23 cm", "42–48 g", "25–31 cm", "~15 yr",
  "NE:c97 SE:c95 MW:c95 SW:u60 TX:c92",
  "The state bird of seven states, more than any other. Unusually, the female sings too — often from the nest, apparently telling the male when to bring food. The male's red comes entirely from carotenoids in his diet.",
  "Brilliant scarlet all over, with a black face mask and throat, a tall crest, and a heavy orange-red bill.",
  "Warm buff-brown with red edging on the crest, wings and tail, and the same orange bill and dark face.",
  ["Seeds", "Sunflower seeds", "Berries", "Insects"],
  "Dense shrubs, woodland edge, thickets, and gardens. Perhaps the most beloved feeder bird in America."),

S("Rose-breasted Grosbeak", "Pheucticus ludovicianus", "Passeriformes", "🐦", ["songbird"],
  "18–22 cm", "35–65 g", "29–33 cm", "7–14 yr",
  "NE:c60 SE:u50 MW:c60",
  "The male sings a rich, liquid warble — like a robin that took singing lessons — and unusually, he sings while sitting on the eggs. His arrival at feeders each May is a highlight of the eastern spring.",
  "Black head and back, white underparts, and a bold triangular blood-red bib. Massive pale bill.",
  "Heavily brown-streaked with a bold white eyebrow and two white wingbars — often mistaken for a big sparrow.",
  ["Seeds", "Insects", "Berries", "Sunflower seeds"],
  "Mature deciduous forest and forest edge. A frequent spring feeder visitor."),

S("Black-headed Grosbeak", "Pheucticus melanocephalus", "Passeriformes", "🐦", ["songbird"],
  "18–19 cm", "35–49 g", "32 cm", "~10 yr",
  "NW:c70 CA:c75 SW:c70 MW:u45",
  "One of the very few birds that can safely eat monarch butterflies, tolerating the toxins the monarchs store from milkweed. Both sexes sing, and both incubate.",
  "Rich burnt-orange body with a black head, and black wings boldly marked with white.",
  "Warm buff with brown streaking, a bold white eyebrow, and a lightly streaked breast.",
  ["Seeds", "Insects", "Berries", "Monarch butterflies"],
  "Open woodland, riparian corridors, and suburbs with mature trees in the West."),

S("Indigo Bunting", "Passerina cyanea", "Passeriformes", "🐦", ["songbird"],
  "11–15 cm", "12–18 g", "18–23 cm", "~10 yr",
  "NE:c65 SE:c70 MW:c68 TX:u55",
  "There is no blue pigment in the feathers at all — the color is a trick of light scattering, so in shade the bird looks flat black. Migrates at night, navigating by the stars, which it learns as a nestling.",
  "Dazzling electric blue all over in summer; brown with blue flecks in winter. Heavy conical bill.",
  "Plain warm brown with faint breast streaking and a whitish throat.",
  ["Seeds", "Insects", "Berries", "Grass seeds"],
  "Brushy field edges, roadsides, and second growth. Sings from exposed high perches all summer long."),

S("Painted Bunting", "Passerina ciris", "Passeriformes", "🐦", ["songbird"],
  "12–14 cm", "13–19 g", "21–23 cm", "~12 yr",
  "TX:c70 SE:u55 SW:u45",
  "Arguably the most gaudily colored bird in North America — so much so that first-time viewers often assume it escaped from a cage. Declining, and long trapped illegally for the cage-bird trade.",
  "Almost unreal: a violet-blue head, a lime-green back, and a blazing scarlet breast and rump.",
  "Bright yellow-green above and paler lemon below — the only truly green finch-like bird in North America.",
  ["Seeds", "Grass seeds", "Insects"],
  "Brushy field edges, thickets, and woodland borders in the south-central states."),

S("Scarlet Tanager", "Piranga olivacea", "Passeriformes", "🐦", ["songbird"],
  "16–19 cm", "23–38 g", "25–29 cm", "~10 yr",
  "NE:c60 SE:u50 MW:u55",
  "A shocking splash of red high in the summer canopy — and yet easy to miss, because it stays up top and sings a burry, hoarse song often described as a robin with a sore throat.",
  "Blazing scarlet body with jet-black wings and tail. Nothing else looks remotely like it.",
  "Olive-yellow with darker olive wings — completely different from the male, and easy to overlook.",
  ["Insects", "Caterpillars", "Beetles", "Berries"],
  "Mature deciduous forest, especially oaks. Forages high in the canopy."),

S("Western Tanager", "Piranga ludoviciana", "Passeriformes", "🐦", ["songbird"],
  "16–19 cm", "24–36 g", "29 cm", "~7 yr",
  "NW:c70 CA:c70 SW:c65 MW:u40",
  "Gets the red pigment for its head from its diet — it can't manufacture it, and likely obtains it from insects that have eaten plants containing it. A flash of flame in a green conifer.",
  "Bright yellow body with black wings and back and a flaming red-orange head.",
  "Yellow-green overall with grey wings and two pale wingbars. No red on the head.",
  ["Insects", "Wasps", "Fruit", "Berries"],
  "Open coniferous and mixed forest in the West, especially in the mountains."),


# ══════════════════════════════════════════════════════════════════
# BLACKBIRDS · ORIOLES
# ══════════════════════════════════════════════════════════════════

S("Red-winged Blackbird", "Agelaius phoeniceus", "Passeriformes", "🐦", ["songbird"],
  "17–23 cm", "32–77 g", "31–40 cm", "~15 yr",
  "NE:c92 SE:c90 MW:c95 NW:c90 SW:c85 CA:c92 TX:c90",
  "Among the most abundant birds in North America. Males are ferociously territorial and will attack anything near the nest — horses, dogs, hawks, and joggers included. The liquid 'conk-la-REE!' is the sound of spring marshes.",
  "Glossy black with brilliant red-and-yellow shoulder epaulettes, flared in display and hidden when not.",
  "Heavily streaked dark brown and buff with a pale eyebrow — looks like a large, dark sparrow.",
  ["Seeds", "Grain", "Insects", "Caterpillars"],
  "Cattail marshes, wet fields, and roadside ditches. Also farm fields and pastures."),

S("Brown-headed Cowbird", "Molothrus ater", "Passeriformes", "🐦", ["songbird"],
  "17–22 cm", "38–64 g", "36 cm", "~17 yr",
  "NE:c80 SE:c80 MW:c85 NW:c75 SW:c72 CA:c78 TX:c80",
  "North America's most notorious brood parasite, laying its eggs in the nests of over 220 species. It followed bison herds historically, which is why it never settled long enough to raise its own young. Forest fragmentation has let it spread devastatingly.",
  "Glossy green-black body with a distinctly brown head and a stout conical bill.",
  "Uniform dull grey-brown with faint streaking and a pale throat — remarkably featureless.",
  ["Seeds", "Grain", "Insects", "Grasshoppers"],
  "Woodland edge, farmland, pastures, and suburbs. Follows livestock as it once followed bison."),

S("Common Grackle", "Quiscalus quiscula", "Passeriformes", "🐦", ["songbird"],
  "28–34 cm", "74–142 g", "36–46 cm", "~22 yr",
  "NE:c88 SE:c88 MW:c90 TX:c80",
  "Overlooked because it's everywhere, but a genuinely striking bird in good light. It soaks hard food in water to soften it, and will raid other birds' nests. Winter roosts can number in the millions.",
  "Iridescent bronze body with a glossy blue-purple head, pale yellow eyes, and a long keel-shaped tail.",
  "Duller and browner with less iridescence and a shorter, less keeled tail.",
  ["Grain", "Seeds", "Insects", "Eggs", "Refuse"],
  "Open woods, lawns, parks, farm fields, and marshes. Roosts communally in enormous flocks."),

S("Great-tailed Grackle", "Quiscalus mexicanus", "Passeriformes", "🐦", ["songbird"],
  "38–46 cm", "115–230 g", "48–58 cm", "~12 yr",
  "TX:c88 SW:c85 CA:c70 MW:u45",
  "Has expanded explosively northward — a century ago it barely reached Texas, and it's now in a dozen more states. Roosts by the thousands in parking lots and city trees, producing a genuinely deafening racket.",
  "Glossy iridescent purple-black with a huge keel-shaped tail and staring pale yellow eyes.",
  "Much smaller than the male and entirely different — warm buff-brown with a paler throat and a shorter tail.",
  ["Insects", "Grain", "Refuse", "Eggs", "Small vertebrates"],
  "Towns, parking lots, farmland, and marshes. Thrives on human landscapes in the Southwest."),

S("Baltimore Oriole", "Icterus galbula", "Passeriformes", "🐦", ["songbird"],
  "17–22 cm", "22–42 g", "23–32 cm", "~11 yr",
  "NE:c72 SE:u55 MW:c72 TX:u50",
  "Weaves a remarkable hanging pouch nest from plant fibers and string, suspended from the tip of a high branch. Comes readily to orange halves and grape jelly — one of the few birds you can reliably lure with fruit.",
  "Flaming orange body with a solid black hood, black wings with a white bar, and an orange-and-black tail.",
  "Yellow-orange below and olive-brown above, with two white wingbars. Older females can be quite orange.",
  ["Nectar", "Fruit", "Caterpillars", "Insects", "Grape jelly"],
  "Open deciduous woodland, riverside trees, parks, and leafy suburbs — especially tall elms and cottonwoods."),

S("Bullock's Oriole", "Icterus bullockii", "Passeriformes", "🐦", ["songbird"],
  "17–19 cm", "29–43 g", "31 cm", "~9 yr",
  "NW:c70 CA:c75 SW:c72 TX:c65 MW:u45",
  "The western counterpart of the Baltimore Oriole, with which it hybridizes where the ranges overlap on the Great Plains. Unlike most orioles it will readily puncture and rob nectar from flowers.",
  "Bright orange with a black crown, back and throat stripe, an orange face, and a huge white wing patch.",
  "Yellowish head and tail with a grey back and a pale belly — much plainer than the male.",
  ["Nectar", "Fruit", "Insects", "Caterpillars"],
  "Riparian woodland, cottonwoods, orchards, and suburban trees in the West."),

S("Western Meadowlark", "Sturnella neglecta", "Passeriformes", "🐦", ["songbird"],
  "16–26 cm", "89–115 g", "41 cm", "~8 yr",
  "MW:c80 NW:c78 SW:c70 CA:c72 TX:c70",
  "The state bird of six states. Its flute-like, gurgling song is the defining sound of the western prairie — and Audubon named it 'neglecta' because everyone before him had overlooked it as just an Eastern Meadowlark.",
  "Brilliant yellow underparts crossed by a bold black V on the chest; cryptic brown streaked back.",
  "Identical to the male but slightly duller and smaller.",
  ["Insects", "Grasshoppers", "Seeds", "Grain"],
  "Grassland, prairie, pasture, and hayfields. Sings from fenceposts and wires."),


# ══════════════════════════════════════════════════════════════════
# FINCHES
# ══════════════════════════════════════════════════════════════════

S("House Finch", "Haemorhous mexicanus", "Passeriformes", "🐦", ["songbird"],
  "12–15 cm", "16–27 g", "20–25 cm", "~3 yr",
  "NE:c88 SE:c85 MW:c88 NW:c85 SW:c88 CA:c92 TX:c85",
  "A western bird, illegally sold in New York as the 'Hollywood Finch' and released around 1940 when the law caught up. Those few birds seeded the entire eastern population, which has since met the westward-spreading originals.",
  "Rosy-red head, breast and rump with a brown streaked back. Red intensity depends on diet — redder males are healthier.",
  "Plain grey-brown with blurry streaking below and no distinct face pattern at all.",
  ["Seeds", "Buds", "Berries", "Sunflower seeds"],
  "Towns, suburbs, farms, and parks. Nests in shrubs, hanging baskets, and building crevices."),

S("Purple Finch", "Haemorhous purpureus", "Passeriformes", "🐦", ["songbird"],
  "12–16 cm", "18–32 g", "22–26 cm", "~14 yr",
  "NE:u60 SE:u50 MW:u55 NW:u60 CA:u55",
  "Roger Tory Peterson memorably described the male as looking 'like a sparrow dipped in raspberry juice'. Steadily losing ground to the introduced House Finch wherever the two overlap.",
  "Raspberry-red wash over the whole head, breast and back — richer and more extensive than a House Finch.",
  "Boldly streaked brown and white with a strong white eyebrow and dark cheek patch — a much crisper face than a female House Finch.",
  ["Seeds", "Buds", "Berries", "Insects"],
  "Coniferous and mixed forest; feeders and woodland edge in winter."),

S("American Goldfinch", "Spinus tristis", "Passeriformes", "🐦", ["songbird"],
  "11–13 cm", "11–20 g", "19–22 cm", "6–11 yr",
  "NE:c90 SE:c85 MW:c90 NW:c80 SW:u60 CA:c80 TX:c75",
  "The strictest vegetarian of any North American songbird — even the nestlings get almost no insects. It nests in late summer, timed to the thistle seed crop, long after every other songbird is done.",
  "Summer: brilliant canary-yellow with a black cap, black wings, and white wingbars. Winter: drab olive-buff.",
  "Duller yellow-olive with no black cap; in winter, plain buffy-grey.",
  ["Thistle seed", "Nyjer", "Sunflower seeds", "Dandelion"],
  "Weedy fields, roadsides, gardens, and woodland edge. Abundant at nyjer feeders."),

S("Pine Siskin", "Spinus pinus", "Passeriformes", "🐦", ["songbird"],
  "11–14 cm", "12–18 g", "18–22 cm", "~9 yr",
  "NE:u55 SE:u45 MW:u50 NW:c65 CA:u55 SW:u50",
  "An irruptive nomad — in years when the northern conifer cone crop fails, siskins pour south by the millions, then may vanish entirely the following winter. Can pack enough seed in its crop to survive a night at −70°F.",
  "Heavily streaked brown and buff with subtle yellow flashes in the wings and tail, and a sharply pointed bill.",
  "Identical to the male, typically with less yellow in the wing.",
  ["Conifer seeds", "Nyjer", "Thistle", "Alder seeds"],
  "Conifer forest; in irruption years, feeders and weedy fields far to the south."),

S("Lesser Goldfinch", "Spinus psaltria", "Passeriformes", "🐦", ["songbird"],
  "9–11 cm", "8–11 g", "15–20 cm", "~7 yr",
  "CA:c80 SW:c78 TX:c65 NW:u50",
  "A tiny, energetic goldfinch of the West, and an accomplished mimic — it works snippets of other species' calls into its rambling song.",
  "Bright yellow below with a black cap and a glossy black or greenish back, plus white wing flashes.",
  "Olive-green above and dull yellow below, with no black cap.",
  ["Thistle", "Sunflower", "Weed seeds", "Buds"],
  "Open woodland, weedy fields, gardens, and streamside thickets in the West."),
