# ══════════════════════════════════════════════════════════════════
# WOODPECKERS
# ══════════════════════════════════════════════════════════════════

S("Red-bellied Woodpecker", "Melanerpes carolinus", "Piciformes", "🐦", ["woodpecker"],
  "22–27 cm", "56–91 g", "38–46 cm", "~12 yr",
  "NE:c85 SE:c88 MW:c85 TX:c75",
  "Badly named — the red belly is a faint pink wash you'll almost never see, while the flaming red cap is obvious. It has expanded steadily northward over the last century and is now a feeder staple.",
  "Boldly black-and-white barred back with red running from the bill all the way over the crown to the nape.",
  "Same zebra back, but red only on the nape — the crown is grey. This is the easiest way to sex them.",
  ["Insects", "Acorns", "Seeds", "Berries", "Suet"],
  "Deciduous woods, parks, and wooded suburbs. Very common at suet and sunflower feeders."),

S("Red-headed Woodpecker", "Melanerpes erythrocephalus", "Piciformes", "🐦", ["woodpecker"],
  "19–25 cm", "56–91 g", "42 cm", "~10 yr",
  "MW:u55 SE:u55 NE:u40 TX:u50",
  "One of only four woodpeckers that stores food, and the only one that covers the cache with wood or bark. Declining sharply as dead trees are cleared and oak savanna disappears.",
  "Unmistakable: an entirely crimson head, snow-white underparts, and black wings with huge white patches.",
  "Identical to the male. Juveniles have brown heads and are often mistaken for a different species.",
  ["Insects", "Acorns", "Beechnuts", "Berries", "Eggs"],
  "Open oak woodland, savanna, dead timber in swamps, and roadside snags. Needs standing dead wood."),

S("Downy Woodpecker", "Dryobates pubescens", "Piciformes", "🐦", ["woodpecker"],
  "14–17 cm", "21–28 g", "25–31 cm", "~5 yr",
  "NE:c92 SE:c88 MW:c92 NW:c85 CA:c80 TX:c80",
  "The smallest woodpecker in North America and by far the most familiar. Its short bill lets it forage on weed stems and thin twigs where bigger woodpeckers can't go.",
  "Black and white with a white back stripe, a small stubby bill, and a red patch on the back of the head.",
  "Identical but with no red at all on the head. Otherwise inseparable from the male.",
  ["Beetle larvae", "Ants", "Berries", "Sunflower seeds", "Suet"],
  "Woods, parks, orchards, and suburbs with trees. A cornerstone of winter mixed flocks with chickadees."),

S("Hairy Woodpecker", "Dryobates villosus", "Piciformes", "🐦", ["woodpecker"],
  "18–26 cm", "40–95 g", "33–43 cm", "~15 yr",
  "NE:c68 SE:c65 MW:c68 NW:c70 SW:u55 CA:c65 TX:u55",
  "Essentially a Downy Woodpecker scaled up, and one of the great beginner ID challenges. The giveaway is the bill: on a Hairy it's nearly as long as the head is wide; on a Downy it's a stub.",
  "Black and white with a white back stripe and a long, chisel-like bill. Red patch on the back of the head.",
  "Same pattern, no red on the head. Size and bill length separate her from a female Downy.",
  ["Wood-boring beetle larvae", "Carpenter ants", "Seeds", "Suet"],
  "Mature forest of all kinds, from boreal to montane to eastern hardwood. Prefers larger trees than Downy."),

S("Northern Flicker", "Colaptes auratus", "Piciformes", "🐦", ["woodpecker"],
  "28–36 cm", "86–167 g", "42–54 cm", "~9 yr",
  "NE:c78 SE:c75 MW:c78 NW:c80 SW:c70 CA:c78 TX:c72",
  "The woodpecker that feeds on the ground, hammering into ant colonies with a barbed, sticky tongue that extends two inches past the bill. Eastern birds flash gold under the wings; western birds flash salmon-red.",
  "Brown with black barring, a black bib, a spotted belly, and a black moustache stripe. Red nape crescent in the East.",
  "Identical, but with no moustache stripe — the cleanest sex mark of any North American woodpecker.",
  ["Ants", "Beetles", "Berries", "Seeds"],
  "Open woodland, parks, and suburbs. Very often seen probing lawns and bare ground for ants."),

S("Pileated Woodpecker", "Dryocopus pileatus", "Piciformes", "🐦", ["woodpecker"],
  "40–49 cm", "250–350 g", "66–75 cm", "~9 yr",
  "NE:u60 SE:c65 MW:u55 NW:u60",
  "Crow-sized, and the largest woodpecker in North America now that the Ivory-billed is almost certainly gone. It chisels distinctive rectangular holes so deep they can snap small trees in half.",
  "Huge black bird with a flaming red crest, a white neck stripe, and a red moustache stripe.",
  "Same, but the forecrown is grey-black rather than red, and she has no red moustache.",
  ["Carpenter ants", "Beetle larvae", "Berries", "Nuts"],
  "Mature forest with large dead trees. Needs big timber, but tolerates wooded suburbs with old trees."),

S("Acorn Woodpecker", "Melanerpes formicivorus", "Piciformes", "🐦", ["woodpecker"],
  "19–23 cm", "65–90 g", "35–43 cm", "~17 yr",
  "CA:c75 SW:c70",
  "Lives in cooperative family groups that maintain a communal 'granary' tree — a single snag can be drilled with 50,000 holes, each holding one acorn. Group members spend the winter guarding it.",
  "Clownish black-and-white face with a red cap, white eyes, and a black bib. Looks permanently startled.",
  "Same, but with a black band separating the red crown from the white forehead.",
  ["Acorns", "Insects", "Tree sap", "Fruit"],
  "Oak and pine-oak woodland. Absolutely dependent on oaks and on standing dead trees for granaries."),


# ══════════════════════════════════════════════════════════════════
# FLYCATCHERS
# ══════════════════════════════════════════════════════════════════

S("Eastern Phoebe", "Sayornis phoebe", "Passeriformes", "🐦", ["songbird"],
  "14–17 cm", "16–21 g", "26–28 cm", "~10 yr",
  "NE:c78 SE:c70 MW:c78 TX:u60",
  "One of the earliest migrants to return each spring, and the subject of the first bird-banding experiment in North America — Audubon tied silver thread to nestlings' legs in 1804 to prove they came back.",
  "Plain grey-brown above, whitish below, with a dark head and no eye-ring or wingbars. Wags its tail constantly.",
  "Identical to the male. Both are best told by the tail-wag and the raspy 'FEE-bee' call.",
  ["Flying insects", "Wasps", "Beetles", "Berries"],
  "Woodland edges near water. Nests under bridges, eaves, and culverts — almost always on a man-made structure."),

S("Say's Phoebe", "Sayornis saya", "Passeriformes", "🐦", ["songbird"],
  "17–20 cm", "21 g", "33 cm", "~7 yr",
  "SW:c70 NW:u55 CA:u60 TX:u55 MW:u40",
  "A phoebe of dry open country, hovering over sagebrush and desert scrub. Nests further north than any other flycatcher, reaching the Arctic coast of Alaska.",
  "Soft grey-brown above with a warm cinnamon belly and a black tail. Wags the tail like other phoebes.",
  "Identical to the male. Both hover and sally after insects from low perches.",
  ["Flying insects", "Beetles", "Grasshoppers", "Spiders"],
  "Desert, sagebrush, badlands, and ranchland. Nests on cliff ledges, barns, and abandoned buildings."),

S("Great Crested Flycatcher", "Myiarchus crinitus", "Passeriformes", "🐦", ["songbird"],
  "17–21 cm", "27–40 g", "30–37 cm", "~7 yr",
  "NE:c62 SE:c68 MW:c62 TX:u55",
  "A cavity-nesting flycatcher with a strange habit: it lines the nest with shed snakeskin, or failing that, cellophane and plastic wrappers. The reason is still argued over — perhaps to deter predators.",
  "Grey throat, bright lemon-yellow belly, rufous tail and wing panels, and a shaggy crest.",
  "Identical to the male. Both are far more often heard — a loud rising 'WHEEP!' — than seen in the canopy.",
  ["Flies", "Beetles", "Caterpillars", "Berries"],
  "Mature deciduous forest and wooded suburbs. Forages high; nests in natural cavities and nest boxes."),

S("Western Kingbird", "Tyrannus verticalis", "Passeriformes", "🐦", ["songbird"],
  "20–24 cm", "37–46 g", "38–41 cm", "~6 yr",
  "SW:c75 CA:c70 TX:c75 MW:c65 NW:c65",
  "A pugnacious flycatcher that fearlessly harasses hawks and ravens many times its size, chasing them out of its territory with a machine-gun chatter.",
  "Pale grey head and chest, lemon-yellow belly, and a black tail edged crisply in white.",
  "Identical to the male. The hidden red crown patch is rarely visible in either sex.",
  ["Flying insects", "Grasshoppers", "Bees", "Berries"],
  "Open country with scattered trees — ranchland, roadsides, fencelines, and town edges."),

S("Eastern Kingbird", "Tyrannus tyrannus", "Passeriformes", "🐦", ["songbird"],
  "19–23 cm", "33–55 g", "33–38 cm", "~10 yr",
  "NE:c70 SE:c65 MW:c72 NW:u55 TX:u60",
  "The scientific name means 'tyrant of tyrants' and it earns it — a kingbird will ride a hawk's back, pecking, until it leaves. On the Amazon wintering grounds it becomes a peaceable fruit-eater in flocks.",
  "Slate-black above, white below, with a white terminal band across the tail like a dipped paintbrush.",
  "Identical to the male. The concealed red crown stripe is almost never seen.",
  ["Flying insects", "Bees", "Beetles", "Berries"],
  "Open fields, orchards, and pond edges with scattered perches — fences, wires, and dead branches."),

S("Scissor-tailed Flycatcher", "Tyrannus forficatus", "Passeriformes", "🐦", ["songbird"],
  "22–38 cm", "36–43 g", "38 cm", "~10 yr",
  "TX:c85 MW:u50 SW:u45",
  "Oklahoma's state bird and one of the most elegant in North America. The male's streamers can nearly double his body length, and he uses them in an aerobatic 'sky dance' display of tumbles and reverses.",
  "Pale grey with salmon-pink flanks and an extraordinarily long forked black-and-white tail.",
  "Same pattern, but with a distinctly shorter tail and paler pink sides.",
  ["Grasshoppers", "Crickets", "Beetles", "Flying insects"],
  "Open grassland, prairie, ranchland, and roadside fences with scattered trees."),


# ══════════════════════════════════════════════════════════════════
# VIREOS
# ══════════════════════════════════════════════════════════════════

S("Red-eyed Vireo", "Vireo olivaceus", "Passeriformes", "🐦", ["songbird"],
  "13–14 cm", "12–26 g", "22–25 cm", "~10 yr",
  "NE:c72 SE:c72 MW:c72 NW:u55 TX:u55",
  "Nicknamed 'the preacher bird' — a single male can deliver over 20,000 song phrases in one day, still going in the noon heat when every other bird has gone quiet. One of the most abundant birds in eastern forests.",
  "Olive-green above, white below, with a grey crown, a bold white eyebrow bordered in black, and a red eye.",
  "Identical to the male. The red iris looks dark in poor light and takes a year to develop.",
  ["Caterpillars", "Insects", "Berries"],
  "Deciduous forest canopy and woodland edge. Forages methodically through the leaves, high up."),

S("Warbling Vireo", "Vireo gilvus", "Passeriformes", "🐦", ["songbird"],
  "12–13 cm", "10–16 g", "22 cm", "~13 yr",
  "NE:c65 MW:c65 NW:c70 SW:u55 CA:c70 TX:u50",
  "About as plain a bird as exists in North America — and then it opens its mouth and delivers a rich, rolling warble. Birders learn it by voice and give up on the plumage.",
  "Drab grey-olive above, whitish below, with a pale eyebrow and no wingbars. Genuinely featureless.",
  "Identical to the male. Both sexes sing, which is unusual among vireos.",
  ["Caterpillars", "Insects", "Berries"],
  "Deciduous woodland, especially cottonwoods and willows along rivers, plus parks and orchards."),

S("White-eyed Vireo", "Vireo griseus", "Passeriformes", "🐦", ["songbird"],
  "11–13 cm", "10–14 g", "18–19 cm", "~7 yr",
  "SE:c70 NE:u35 TX:c65 MW:u40",
  "A skulker of dense thickets with a loud, explosive, oddly mechanical song that often starts and ends with a sharp 'chick!'. Frequently mimics snatches of other species' calls.",
  "Olive above with yellow 'spectacles', two white wingbars, yellow flanks, and a startling white iris.",
  "Identical to the male, white iris and all. Juveniles have dark eyes that pale over the first year.",
  ["Insects", "Caterpillars", "Berries"],
  "Dense shrubby thickets, briar tangles, and overgrown fields. Heard far more often than seen."),


# ══════════════════════════════════════════════════════════════════
# CORVIDS — jays, crows, ravens, magpies
# ══════════════════════════════════════════════════════════════════

S("Blue Jay", "Cyanocitta cristata", "Passeriformes", "🐦", ["songbird"],
  "22–30 cm", "70–100 g", "34–43 cm", "~7 yr",
  "NE:c95 SE:c92 MW:c95 TX:c75",
  "Mimics hawk calls convincingly, apparently to scatter birds from a feeder before dropping in. Also one of the great foresters — a single jay may cache thousands of acorns a year, and the ones it forgets become oak trees.",
  "Brilliant blue above with a black necklace, white wingbars and tail corners, and a bold crest. The blue is structural, not pigment.",
  "Identical to the male. Sexes cannot be reliably told apart in the field.",
  ["Acorns", "Seeds", "Insects", "Eggs", "Nuts"],
  "Woodlands, parks, and suburbs with oaks. Bold, loud, and a fixture at feeders."),

S("Steller's Jay", "Cyanocitta stelleri", "Passeriformes", "🐦", ["songbird"],
  "30–34 cm", "100–140 g", "45 cm", "~16 yr",
  "NW:c85 CA:c80 SW:c65",
  "The Blue Jay's western counterpart, and the only crested jay west of the Rockies. Bold to the point of larceny around campsites and picnic tables.",
  "Sooty-black head and shaggy crest blending into a deep blue body and wings. Often shows pale streaks on the forehead.",
  "Identical to the male. Highly vocal, with a harsh shook-shook-shook and a good Red-tailed Hawk imitation.",
  ["Seeds", "Nuts", "Insects", "Eggs", "Picnic scraps"],
  "Coniferous and pine-oak forest, especially in mountains. Common around campgrounds and mountain towns."),

S("California Scrub-Jay", "Aphelocoma californica", "Passeriformes", "🐦", ["songbird"],
  "27–31 cm", "70–100 g", "39 cm", "~9 yr",
  "CA:c85 NW:u55",
  "A crestless jay with a remarkable memory — it remembers not just where it cached food but what it cached and how long ago, retrieving perishable items first. It also re-hides food if it noticed another jay watching.",
  "Deep azure head, wings and tail, a grey-brown back patch, a white eyebrow, and a partial blue necklace.",
  "Identical to the male. Pairs stay together year-round on a defended territory.",
  ["Acorns", "Insects", "Seeds", "Eggs", "Lizards"],
  "Oak woodland, chaparral, scrub, and suburban gardens throughout California."),

S("American Crow", "Corvus brachyrhynchos", "Passeriformes", "🐦", ["songbird"],
  "40–53 cm", "316–620 g", "85–100 cm", "8–15 yr",
  "NE:c95 SE:c92 MW:c95 NW:c92 SW:u65 CA:c92 TX:c88",
  "Recognizes individual human faces, holds grudges, and teaches those grudges to its offspring. Uses tools, solves multi-step puzzles, and gathers in winter roosts that can exceed a hundred thousand birds.",
  "Entirely glossy black with a heavy bill and a fan-shaped tail. Iridescent purple sheen in good light.",
  "Identical to the male. Young from previous years often stay to help raise the next brood.",
  ["Almost anything — insects, grain, carrion, eggs, refuse"],
  "Extraordinarily adaptable. Farmland, city streets, parks, beaches, and landfills. Avoids only deep forest."),

S("Common Raven", "Corvus corax", "Passeriformes", "🐦", ["songbird"],
  "54–67 cm", "0.7–2 kg", "116–153 cm", "~20 yr",
  "NW:c80 SW:c80 CA:c70 NE:u55 MW:u45 TX:u50",
  "Arguably the most intelligent bird alive. Ravens plan for the future, deceive rivals about cache locations, play — sliding down snowbanks apparently for fun — and have been seen leading wolves to carcasses they can't open themselves.",
  "Large, all black, with a heavy bill, shaggy throat hackles, and a wedge-shaped tail. Soars and tumbles in flight.",
  "Identical to the male. Pairs mate for life and hold territories for years.",
  ["Carrion", "Rodents", "Eggs", "Insects", "Grain", "Refuse"],
  "Mountains, deserts, coasts, forest, and tundra. Increasingly common in western towns."),

S("Black-billed Magpie", "Pica hudsonia", "Passeriformes", "🐦", ["songbird"],
  "45–60 cm", "145–210 g", "56–61 cm", "~9 yr",
  "NW:c75 MW:u50 SW:u50",
  "Builds a huge domed stick nest with a roof, taking up to 40 days to construct. Holds 'funerals' — groups gather and call loudly around a dead magpie before dispersing.",
  "Striking black and white with an extremely long iridescent green-blue tail, flashing white wing patches in flight.",
  "Identical to the male, with a slightly shorter tail.",
  ["Insects", "Carrion", "Seeds", "Eggs", "Small mammals"],
  "Open country with scattered trees — sagebrush, ranchland, streamside thickets, and town edges in the West."),
